### ISSUE TITLE
Uploading from base64 to S3 trouble

### ISSUE THREAD

**Issue by TakteS** [stavro/arc#118]
Hello. I want to upload images from base64 strings: `%{filename: "photo.png", binary: binary |> Base.decode64!}` (like you show at #107 ) to S3 storage and I have an error:

```
[error] Task #PID<0.673.0> started from #PID<0.663.0> terminating
** (MatchError) no match of right hand side value: %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<InitiateMultipartUploadResult xmlns=\"http:
//s3.amazonaws.com/doc/2006-03-01/\"><Bucket>ave88-test</Bucket><Key>uploads/properties/665/47e081b4-6af9-4b90-b2ca-dbe5652786af/large.png</Key><Upl
oadId>...--</UploadId></InitiateMultipartUploadResult>", headers:
 [{"x-amz-id-2", "..."}, {"x-amz-request-id", "..."}, {"Date", "Thu, 20 Oc
t 2016 09:35:06 GMT"}, {"Transfer-Encoding", "chunked"}, {"Server", "AmazonS3"}], status_code: 200}
    (ex_aws) lib/ex_aws/s3/upload.ex:39: ExAws.S3.Upload.initialize!/2
    (ex_aws) lib/ex_aws/s3/upload.ex:80: ExAws.Operation.ExAws.S3.Upload.perform/2
    (arc) lib/arc/storage/s3.ex:53: Arc.Storage.S3.do_put/3
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5

    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.113666932/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
```

I checked the created dir on the my S3 bucket, and I found that only original.png was saved and other versions of file isn't created. 

When I do the same operation, but with Locale storage it's works as well

I use arc _0.6.0-rc1_ and ex_aws _1.0.0-rc.3_ versions. How do you think, it's arc or ex_aws trouble?

**Comment by TakteS** [comment]
Look at the code, maybe it can help:

```
# photos is a list of binaries
photos = photos |> Enum.map(&(%{filename: "photo.png", binary: &1 |> Base.decode64!}))

for photo <- photos do
  changeset = Photo.Validator.changeset(%Photo{}, %{property_id: property.id, photo: photo})
  if changeset.valid?, do: changeset |> Repo.insert
end
```

**Comment by benwilson512** [comment]
The issue isn't with the fact that the upload is base64. The issue is that you need to have the `sweet_xml` library available if you want to do multipart uploads. Arc needs to specify the need for this dependency for whichever upload scenario this is.

**Comment by TakteS** [comment]
@benwilson512 Thank you! With `sweet_xml` this works fine

**Comment by benwilson512** [comment]
Awesome. Arc should probably mention the need to add that dependency still.

**Comment by thousandsofthem** [comment]
Adding `sweet_xml` helped me as well, many thanks!
It was hard to figure it out. Please please add something to README about it

**Comment by stavro** [comment]
It is in the README at the top - sweet_xml is listed as a dependency if you're using S3.

I'm thinking about taking all of the s3 related stuff into a separate package so it can have enforceable dependencies rather than the optional stuff currently.

**Comment by benwilson512** [comment]
Not a bad idea. I wish I could make them non optional for ExAws but it doesn't make any sense to do so as there are lots of people who use it for other AWS services that do not use XML.
