### ISSUE TITLE
arc_manta: support for Joyent Manta using Arc

### ISSUE THREAD

**Issue by onyxrev** [stavro/arc#120]
Thanks for this great library!

I've made this:

https://github.com/onyxrev/arc_manta

It's not perfect, I'm sure, but it works and I'm using it in a couple of my projects. It's got some basic test coverage but is missing some of the features of the S3 storage backend such as signed urls (should be possible) and some of the metadata fanciness.

This is basically just a heads up. Feel free to leave feedback, contribute, merge, ignore or what have you.

**Comment by stavro** [comment]
Amazing!

I'll add this to the README

**Comment by onyxrev** [comment]
Awesome! I need to get it up on hex.

**Comment by stavro** [comment]
Added to the README :)
