### ISSUE TITLE
Remote File / URL storage is not working.

### ISSUE THREAD

**Issue by pejrich** [stavro/arc#126]
I am storing files from the backend (no upload via form). All my uploads are from URLs. So instead of storing the file locally, I want to just store directly from the URL (as mentioned in the docs).

When I try this, I get an error:

```
PictureUploader.store("https://avatars2.githubusercontent.com/u/1481354?v=3&s=400")            
{:error, :invalid_file}
```

If I try via changeset, it get:

```
Picture.changeset(%Picture{}, %{picture: "https://avatars2.githubusercontent.com/u/1481354?v=3&s=400"})
#Ecto.Changeset<action: nil, changes: %{},
 errors: [picture: {"is invalid", [type: MyApp.PictureUploader.Type]}],
 data: #MyApp.Picture<>, valid?: false>
```

Any idea how to fix this? My uploader has nothing much in it. Do I need to add something to support URL upload?

```
defmodule MyApp.PictureUploader do
  use Arc.Definition
  use Arc.Ecto.Definition

  @versions [:original]
end
```

**Comment by pharosproduction** [comment]
Did you find it? I have the same issue.

**Comment by stavro** [comment]
Are you using master?  Remote files haven't been released to hex yet.  I'll do that soon.

**Comment by pharosproduction** [comment]
it works, thanks. What about to add a scope like with Plug.Upload?

**Comment by pharosproduction** [comment]
There is a small issue. If you will try to use url with "?someparams" at the end of it:
ex. Facebook userpic
[](https://scontent.xx.fbcdn.net/v/t1.0-1/p200x200/12512499_822216874571331_2139759289868198491_n.jpg?oh=fa401203801de150181e914469a64d08&oe=58C81AA5)

than Arc.File doesn't want to load local copy and respond with an error. I have added a small fix to Arc in my project, but it's ugly because I'm new to Elixir. I believe you can make it much better.
```
defp save_file(remote_path) when is_binary(remote_path) do
    [ext | _] = String.split(Path.extname(remote_path), "?")
```
and
```
def new(remote_path = "http" <> _) do
    case save_file(remote_path) do
      {:ok, local_path} ->
        [filename | _] = String.split(Path.basename(remote_path), "?")
        %Arc.File{path: local_path, file_name: filename}
```

**Comment by stavro** [comment]
Can you submit a PR using:

```elixir
uri = URI.parse(remote_path)
filename = Path.basename(uri.path)
```

**Comment by pharosproduction** [comment]
I have added redirect support to httpoison response. Ex. Facebook graph request for an image:
`http://graph.facebook.com/1005201499606200/picture?type=large`

**Comment by pejrich** [comment]
@pharosproduction Is this working for you now? I still can't get it to work. I'm using 0.6.0-rc3. If I try to upload from a URL, I still get the ```{:error, :invalid_file}``` error. I should be able to write ```PictureUploader.store("https://avatars2.githubusercontent.com/u/1481354")``` correct? Above you said, thanks, it works. Did you figure it out?

**Comment by stavro** [comment]
Storing remote files hasn't been pushed to hex yet.  Use master

**Comment by phonezawphyo** [comment]
I got the same `:invalid_file error` but it was due to having `validate/1` function checking extensions but downloaded temporary remote file having no extension in the file_name.
