### ISSUE TITLE
How to test Arc?

### ISSUE THREAD

**Issue by mamantoha** [stavro/arc#128]
I have a test generated by Phoenix for a model `Attachment`:

```
defmodule MyApp.AttachmentTest do
  use MyApp.ModelCase

  alias MyApp.Attachment

  @valid_attrs %{file: "some content"}
  @invalid_attrs %{}

  test "changeset with valid attributes" do
    changeset = Attachment.changeset(%Attachment{}, @valid_attrs)
    assert changeset.valid?
  end

  test "changeset with invalid attributes" do
    changeset = Attachment.changeset(%Attachment{}, @invalid_attrs)
    refute changeset.valid?
  end
end
```

And I receive the error:

```
  1) test changeset with valid attributes (MyApp.AttachmentTest)
     test/models/attachment_test.exs:10
     Expected truthy, got false
     code: changeset.valid?()
     stacktrace:
       test/models/attachment_test.exs:12: (test)
```

How should look `@valid_attrs` that test was successful? 

Thanks!

**Comment by ggerico** [comment]
Put a file in your test directory somewhere (maybe test/attachment_files/) then use the Plug.Upload struct:
`@valid_attrs %{file: "some content", attachment: %Plug.Upload{path: "test/attachment_files/example.png", filename: "example.png"}}`

check this [link](http://stackoverflow.com/questions/33871662/testing-a-file-upload-in-phoenix-elixir).
