### ISSUE TITLE
Decompression bomb protection

### ISSUE THREAD

**Issue by JustMikey** [stavro/arc#13]
I wonder if there is any decompression bomb protection (like [png bomb](https://www.bamsoftware.com/hacks/deflate.html)) and if not, if it's going to be implemented?

**Comment by stavro** [comment]
Does imagemagick have protection for this? What are some of the preferred ways of handling it?

**Comment by JustMikey** [comment]
I've done some research and it appears that the best way to handle it is to pass some parameters to the imagemagick's `limit` flag to limit the memory usage and etc. But I may be wrong so you're probably do your own research.

**Comment by JustMikey** [comment]
https://stackoverflow.com/questions/33602308/how-to-check-png-file-if-its-a-decompression-bomb/33613289#33613289

**Comment by stavro** [comment]
Since all of the arguments of a transformation are supplied to ImageMagick's convert tool directly, you should be able to define the following:

```
def transform(:thumb, _) do
    {:convert, "-limit area 10MB -limit disk 100MB -strip -thumbnail 100x100^ -gravity center -extent 100x100 -format png"}
  end
```

Which should prevent system resources from being completely overwhelmed.  I'll go ahead and add a section in the README.md to note this.

One thing that would be prudent to support is handling errors from ImageMagick for these cases, which `arc` currently does not look for.

**Comment by JustMikey** [comment]
Okay, I think I've found a way to avoid passing params regarding resources' usage. I think the better way might be just checking the image's width and height headers (whether they are in some acceptable range) and if they are not (the bomb file I found on the net had resolution of 225MP x 225MP, which is probably not really acceptable for any website), raise an error or return `{:error, something}` or whatnot.

Also it's worth pointing out that those headers can be forged but as far as I understand imagemagick can detect it and throw an error, which is way I think we need to handle its returns (it will return 1 exit code if imagemagick throws an error)
