### ISSUE TITLE
Params not matching on string keys

### ISSUE THREAD

**Issue by joeswann** [stavro/arc#135]
Not 100% sure if this should be in `arc` or `arc_ecto`. 

Short version of what's happening:
- Model Page has a mtm association to Image
- Image has an attachment 
- Using a JSON endpoint to attempt to `put` an update
- Writing a test to attempt to add an image as part of a json request
- Request looks like this
```
page = Repo.insert! Ap.Factory.page_with_images_changeset
path = api_page_path(conn, :update, page.id)

body = %{
      page:  %{
        id: page.id, 
        images:  [
          %{
            id: List.first(page.images).id
          },
          %{
            name: "Test",
            file: %{
              binary: "binary",
              filename: "test.jpg"
            }
          }
        ]
      }
    } |> Poison.encode!

conn
  |> put_req_header("content-type", "application/json") 
  |> put(path, body)
```

Every thing appears to work perfectly right up until this request, at which point I get this error
```
# Request
%{
  "id" => 696,
  "images" => [
    %{"id" => 790},
    %{
      "file" => %{"filename" => "test.jpg","binary" => "binary"},
      "name" => "Test"
    }
  ]
}

#Error
(FunctionClauseError) no function clause matching in Arc.File.new/1
stacktrace
lib/arc/file.ex:16: Arc.File.new(%{"filename" => "test.jpg", "binary" => "binary"})
```

What I don't get is why the trace is happening when the matching clause should presumably be
```
#Line 39
def new(%{filename: filename, binary: binary}) do
```

Let me know if there's anything I can do to help here - I think I'm missing something obvious but I can't for the life of me figure out what.

**Comment by joeswann** [comment]
Update, the difference appears to be between this
`%{"filename" => "test.jpg", "binary" => "binary"}`
and this
`%{filename: "test.jpg", binary: "binary"}`

Still clearly have a lot to learn!

**Comment by joeswann** [comment]
I think this is actually happening on arc_ecto's cast_attachments, which should be changing keys to atoms anyway. Going to close this and do some more digging.

**Comment by aislanmaia** [comment]
I'm getting the same problem.
