### ISSUE TITLE
Nginx 502 - Due to streaming file to S3?

### ISSUE THREAD

**Issue by snewcomer** [stavro/arc#136]
Problem
===
Been at this problem for a few days.  On the latest arc/ex_aws.  Uploading a photo to S3 locally on my mac works.  Building a production release on an ubuntu vagrant and deploying to a digital ocean box and trying to upload an image with a PUT request leads to a 502 Nginx Bad Gateway.  I believe there is some type of server configuration that I am missing.  Any quick thoughts?  

error.log
===
`5584#5584: *33 upstream prematurely closed connection while reading response header from upstream`

Here is my ssl/nginx config.  

https://dustinfarris.gitbooks.io/phoenix-continuous-deployment/content/phoenix_server/nginx.html

I know that is may not be an arc issue, but perhaps for documentation if other ppl run into this issue.

**Comment by snewcomer** [comment]
One thing interesting is that if I downgrade to before streaming the S3 upload, S3 was able to log a PUT.  Using the latest release, I get the same error, but no logs.

**Comment by philipgiuliani** [comment]
I had the same problem. It was because the node crashed for some reason. Can you check the erlang logs? In my case i had to install `erlang-xmerl` to get sweet-xml working. My server is Ubuntu 16.04
