### ISSUE TITLE
Duplicating extension

### ISSUE THREAD

**Issue by zion03** [stavro/arc#143]
Rewrite `filename` as described in manual

`def filename(version, {file, scope}) do
  "#{scope.id}_#{version}_#{file.file_name}"
end`

In uploaded file extension is duplicated

**Comment by zion03** [comment]
Also,

Avatar.store(file) -->   {:ok, file}

In this case  `file` contain origin name (as in user`s browser), not like it was stored

**Comment by zion03** [comment]
ping...

**Comment by zion03** [comment]
Hello this library currently maintained? 
I'm using this lib wrong or problems which I mentioned really bugs?
Thanks!

**Comment by stavro** [comment]
To get the file as it is stored, you'll use the `.url` methods.  This will (if local storage), return a path to the file, if S3, return a signed (or unsigned), path to the file on S3.

**Comment by zion03** [comment]
Thanks for the answer. 
What about files extension duplications?

**Comment by zion03** [comment]
Please look for this, extension duplicates only wjen I rewrite `def filename`
By default all works fine.

**Comment by joshuataylor** [comment]
I'm also seeing file extension duplicates on `def filename`.

**Comment by ryanwinchester** [comment]
this should be added to the readme. the current example creates duplicated extensions.
