### ISSUE TITLE
Upload timing out (Task.await time out) when using S3 storage and after upgrade.

### ISSUE THREAD

**Issue by ospaarmann** [stavro/arc#150]
Hi,

I recently upgraded to 

arc:  0.6.0,
arc_ecto:  0.5.0,
ex_aws: 1.0.0,
hackney: 1.6.1,
poison: 2.0,
sweet_xml: 0.5

And I now receive a time out error without a lot of information why the storing of the upload fails. I can narrow it down to the cast_attachments/3 call so my guess is, that something goes wrong when pushing the upload to S3.

My config in config.exs

```
config :ex_aws, :httpoison_opts,
  recv_timeout: 15_000

config :arc,
  version_timeout: 15_000
```

My config in dev.exs

```
config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  region: "eu-central-1"

config :arc,
  storage: Arc.Storage.S3,
  bucket: {:system, "AWS_S3_BUCKET"},
  virtual_host: true
```

The error I receive:

```
[error] #PID<0.1049.0> running MyApp.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /fileapi/v1/tmp-application-avatar
** (exit) exited in: Task.await(%Task{owner: #PID<0.1049.0>, pid: #PID<0.1054.0>, ref: #Reference<0.0.4.4113>}, 15000)
    ** (EXIT) time out
```

I'm quite stuck. Any idea why this happens?

**Comment by naps62** [comment]
@ospaarmann I'm getting the same error, but on a new app.

After seeing your comment I tried downgrading both arc and ex_aws to previous versions, but that didn't change anything

**Comment by taorg** [comment]
Hello @ospaarmann I'm pretty sure you got some mis-configuration.
Or some bug in your code.
I'm working with arc 0.7.0 and everything runs smooth against S3 bucket.

**Comment by mykewould** [comment]
The task is expiring `Task.await(%Task{owner: #PID<0.1049.0>, pid: #PID<0.1054.0>, ref: #Reference<0.0.4.4113>}, 15000)` you can see it set to 15_000 as specified in your config. I just increased my timeout to 30000 for larger files.

```elixir
config :arc,
  version_timeout: 30_000
```

Mileage may vary.

**Comment by speeddragon** [comment]
I have the same issue, I've increased the timeout to 30_000 but still getting 15000 timeout.

**Comment by taorg** [comment]
Hi @speeddragon we solved it, the cause are time outs and probably your network, this error appears when we test our application with cappy internet access.
This is how we solve it :

 1. Adding this to our application config
```
config :ex_aws, :hackney_opts,
        recv_timeout: 300_000
```
 2.  Passing "timeout" parameter when you define Arc the uploader

  ```
def s3_object_headers(version, {file, scope}) do
    [timeout: 3_000_000, content_type: Plug.MIME.path(file.file_name)] # for "image.png", would produce: "image/png"
  end
```

This method does no more than invoke ex_aws S3 methods.
Hope it helps

**Comment by speeddragon** [comment]
I will check with a different ISP (maybe is AWS), I'm from Europe and the S3 bucket is from Singapore. I will test your configuration also, thanks!
