### ISSUE TITLE
Avatar.url() generates old url

### ISSUE THREAD

**Issue by hopeIndustries** [stavro/arc#164]
Hey guys, 

I am not sure if this is intended or not, but when you use `Avatar.url("name.png", %{id: "fold"})` it will generate 
"https://s3.amazonaws.com/bucket.coml/fold/name.png"
 while it should be 
"https://bucket.com.s3.amazonaws.com/fold/name.png"

Any thoughts on this?

**Comment by digitalcake** [comment]
I was trying to look into the use of the domain "https://bucket.com.s3.amazonaws.com"

Where are you getting your information from that S3 should using that subdomain?

**Comment by stavro** [comment]
If you want to generate urls in the virtual host style, add this to your config:

```
config :arc,
  virtual_host: true
```

**Comment by EdoardoLopez** [comment]
Hi, i'm have the same problem, the files that i uploaded has a url generated like if "virtual_host" is set to false, and when use "urls()" methods the urls generated are the correct, without the "/{bucke_name}". 

files uploaded at:
```
[debug] ExAws: Request URL: "https://{bucket}.{region}.digitaloceanspaces.com/{bucket}/cloud_store/images/{filename}"
```
and when use urls() methods is this

```

```%{
  medium: "https://{bucket}.{region}.digitaloceanspaces.com/cloud_store/images/{filename}_medium.png",
  original: "https://{bucket}.{region}.digitaloceanspaces.com/cloud_store/images/{filename}_original.png",
  thumbnail: "https://{bucket}.{region}.digitaloceanspaces.com/cloud_store/images/{filename}_thumbnail.png"
}
