### ISSUE TITLE
How to use UUIDs?

### ISSUE THREAD

**Issue by Quintasan** [stavro/arc#166]
Hi,

I'm trying to store images in directories named using `UUID.uuid4()` as seen [here](https://github.com/asi-pwr/decoction/blob/images-controller/web/uploaders/image_upload.ex#L9). Storing the image works fine but whenever I call `link(image.image.file_name, to: Decoction.ImageUpload.url({image.image, image}, :original))` (eg. every time I refresh my index page) the URL's I get are different and will obviously result in 404 when accessing the files.

What am I doing wrong?

**Comment by Quintasan** [comment]
@stavro My best bet is that this is done by design. Should one store the generated UUID in the record itself as well?

**Comment by jung-hunsoo** [comment]
It seems that the line 12 in the source generates uuid5 for every calling.

To fix it, add a field for UUID to the record.

**Comment by pedep** [comment]
If you wish to store the filename, and still be able to access your file by a uuid5, you probably want to add a column to your database, where you store the uuid (like @jung-hunsoo answered). If you on the other hand don't care about the original filename (which might be the case in many situations), you could try the solution mentioned in #85

**Comment by Quintasan** [comment]
@jung-hunsoo @pedep Alright, thanks.
