### ISSUE TITLE
decouple storage api from arc

### ISSUE THREAD

**Issue by stephenmoloney** [stavro/arc#168]
On a higher level, just wondering if the storage mechanism can be decoupled from the arc
repository using an adapter interface?
Then any adapter fulfilling the adapter behaviour would work in theory.
I'd imagine this would require refactoring, any thoughts on this?

**Comment by stephenmoloney** [comment]
Hang on, I see the `README.md` has been changed a bit since I was here a few months ago. 

I have been writing my own `Arc.Storage` files for `OVH` and `Rackspace`. I'll see about opensourcing them.

Just that sometimes it feels like to me that the repository was centered around S3 and perhaps could be more S3 agnostic with all the adapters in a separate repo.

**Comment by stavro** [comment]
Yes - definitely.

The biggest benefit to extracting the s3-specific stuff into a separate package is better dependency management.  There are too many "optional" dependencies (which are actually required if you use s3).
