### ISSUE TITLE
Add additional case to transform

### ISSUE THREAD

**Issue by hauleth** [stavro/arc#171]
Sometimes I just want to `:ignore` transformation of file, this would mean that I want to provide default instead. Is that possible?

**Comment by hauleth** [comment]
Alternatively it would be great to have possibility to return just string that will contain path for file that should be stored instead.

**Comment by stavro** [comment]
the transformation function can return `:noaction` to indicate that no transformation should take place

**Comment by hauleth** [comment]
`:noaction` is different from `:ignore` in that way that when you return first one you will get URL to the uploaded file on request. On the other hand proposed action would return defined default URL.
