### ISSUE TITLE
Loading image from external URL results in double extensions

### ISSUE THREAD

**Issue by Qqwy** [stavro/arc#174]
I am not entirely certain if this is a bug in `arc` or in `arc_ecto`, but when I load an image from an external URL, such as `http://westchestertreelife.com/files/2015/03/American-Dogwood-Tree-Westchester-Tree-Life.jpg`, and I have a file_name function as follows:

```
  def filename(version, {file, scope}) do
    "#{version}_#{file.file_name}"
  end
```

then I end up with URLs like `http://localhost:4000//uploads/large_thumb_American-Dogwood-Tree-Westchester-Tree-Life.jpg.jpg?v=63658281874`. 

Note the `.jpg.jpg`.

What is going on here? Is this a mistake from my part, or is this a problem in `arc`?

**Comment by ryanwinchester** [comment]
I am getting double extensions in S3, too.

After uploading the photo to S3 and overriding the persisted filenames in the same way you are doing, it then adds the extension to the file again.

My S3 bucket:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/0b3p362i3i06031h3n0B/Screen%20Shot%202017-04-01%20at%206.01.20%20PM.png)

**Comment by stavro** [comment]
README updated to reflect the expected usage of `filename/2`.. essentially the return value of that function should not include an extension.
