### ISSUE TITLE
When trying the example from the README i am getting this gen_server.call error

### ISSUE THREAD

**Issue by vernomcrp** [stavro/arc#2]
If you could give me a few pointers i would really appreciate it! :)
```
** (EXIT from #PID<0.129.0>) exited in: :gen_server.call(:undefined, {:socket, #PID<0.134.0>, 'phoenix-s3-test.s3.amazonaws.com', 443, true}, :infinity)
    ** (EXIT) no process
```

**Comment by sean-atv** [comment]
I might have forgotten to document one step.

In your `mix.exs` file where you list your application dependencies, can you try adding `ssl` and `erlcloud`?

Should look something like this:

```
  def application do
    [
      mod: { MyApp, [] },
      applications: [
        :phoenix,
        :cowboy,
        :logger,
        :postgrex,
        :ecto,
        :ssl,
        :erlcloud
      ]
    ]
  end
```

Let me know if this fixes the issue.

**Comment by stavro** [comment]
I might have forgotten to document one step.

In your `mix.exs` file where you list your application dependencies, can you try adding `ssl` and `erlcloud`?

Should look something like this:

```
  def application do
    [
      mod: { MyApp, [] },
      applications: [
        :phoenix,
        :cowboy,
        :logger,
        :postgrex,
        :ecto,
        :ssl,
        :erlcloud
      ]
    ]
  end
```

Let me know if this fixes the issue.

**Comment by vernomcrp** [comment]
I tried only :erlcloud and it's work. Thank stavro

**Comment by stavro** [comment]
Of course!  Please let me know your experience with arc if you end up using it and any features you feel are missing or would be beneficial.

:) 

Thanks @vernomcrp
