### ISSUE TITLE
Images not displaying in production

### ISSUE THREAD

**Issue by josephan** [stavro/arc#201]
Hello I am trying to upload images on my phoenix app and it worked perfectly locally but in production the resource can't be located. So I get the ripped image instead.
This was the guide I was following: https://medium.com/@Stephanbv/elixir-phoenix-uploading-images-locally-with-arc-b1d5ec88f7a

In prod:
<img width="845" alt="screen shot 2017-06-20 at 1 55 12 pm" src="https://user-images.githubusercontent.com/8878596/27347909-467a4320-55c0-11e7-85b8-4a9b2a388732.png">

In local machine:
<img width="833" alt="screen shot 2017-06-20 at 1 56 08 pm" src="https://user-images.githubusercontent.com/8878596/27347916-4ec007f4-55c0-11e7-9e29-0ea0262ec4a9.png">

I deployed my application using Distillery and Gatling on Digital Ocean Ubuntu 16.04.

I've made sure to add the plug to my endpoint:
```
defmodule Kappamon.Endpoint do
  use Phoenix.Endpoint, otp_app: :kappamon

  #### omitted

  plug Plug.Static,
    at: "/", from: :kappamon, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  plug Plug.Static, 
    at: "/uploads", from: Path.expand("./uploads"), gzip: false

  #### omitted
end

```

Here is my `mix.exs`:
```
defmodule Kappamon.Mixfile do
  use Mix.Project

  #### omitted

  def application do
    [mod: {Kappamon, []},
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex, :exirc, :httpoison, :oauth2, :scrivener_ecto,
                    :timex, :arc_ecto]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [{:phoenix, "~> 1.2.1"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"},
     {:exirc, "~> 1.0"},
     {:distillery, "~> 1.4"},
     {:oauth2, "~> 0.9"},
     {:httpoison, "~> 0.11.1"},
     {:scrivener_ecto, "~> 1.0"},
     {:timex, "~> 3.0"},
     {:arc, "~> 0.8.0"},
     {:arc_ecto, "~> 0.7.0"}]
  end

  #### omitted

end
```

**Comment by pedep** [comment]
Did you end up fixing this? Can we close this issue?

**Comment by josephan** [comment]
I ended up using S3 but it seems Microflow solution will work.

**Comment by pedep** [comment]
Glad to hear you found a solution.

I have a suspicion, that the problem might have had to do with `Path.expand("./uploads")` not resolving to actual place the images got uploaded to

**Comment by lorenzosinisi** [comment]
The problem may also have to do with your nginx config in production. I had a very similar issue and I fixed it in the following way: 
```
sudo apt-get install bindfs
# find the path in which you have defined your Arc uploader
# create a new path in usr/share, I decided for  /usr/share/nginx/root_boxes
sudo bindfs -u www-data -g www-data /root/deploy/yourappname/uploads /usr/share/nginx/root_boxes
# edit your nginx config 
location /uploads {
   autoindex on;
   alias /usr/share/nginx/root_boxes/;
  }
```

I have written a small blog post here https://ngulasort.com/how-to-serve-static-assets-with-elixir-phoenix-and-arc-and-nginx
