### ISSUE TITLE
How to get file metadata?

### ISSUE THREAD

**Issue by ranyefet** [stavro/arc#205]
Hello,

In my app, I allow users to upload audio files [mp3 m4a], I like to convert all files to mp3 and extract the duration of the audio file in milliseconds.

I didn't find any information on how to access file metadata from the documentation.

Maybe it's not related directly to `arc` but since `arc` is handling the upload and transformation, I though it might be related.

Is there a way to access uploaded file metadata? or run a command in one of the steps to extract the data and then saved it to the DB?

Thanks,
Ran.

**Comment by mertonium** [comment]
Hi @ranyefet - I don't think this is in `arc`'s wheelhouse. I realize it's not exactly the same, but fwiw here's how I [extracted exif data from photos](https://www.mertonium.com/extracting-gps-exif-data-from-a-photo-in-phoenix) that I uploaded with `arc`.

**Comment by ranyefet** [comment]
Hi @mertonium, thanks i will look into your blog post.
I ended up just using a background job, to retrieve the file, extract the duration and update the db.
