### ISSUE TITLE
Proposal: Allow default `storage_dir` to be configured

### ISSUE THREAD

**Issue by mayppong** [stavro/arc#207]
Instead of defaulting to "uploads" always, it would be nice to be able to configure this through application config files.

Example:
```
config :arc,
  storage_dir: "/_public/assets"
```

The code would be
```
def storage_dir, do: Application.get_env(:arc, :storage_dir, "uploads")
```
I'm happy to put up a PR for this.

**Comment by njwest** [comment]
Seconded, this would make directory issues easier to deal with when implementing Arc with Phoenix >= 1.3 in production, given the shifting directory structure

**Comment by pedep** [comment]
https://github.com/stavro/arc/pull/210

**Comment by pedep** [comment]
@stavro this can be closed
