### ISSUE TITLE
Moving from erlcloud to ex_aws ?

### ISSUE THREAD

**Issue by JustMikey** [stavro/arc#21]
I think it may be worth it to move from using `erlcloud` to `ex_aws` for accesing S3 services, the latter gives way more useful responses, easier to configure and some other things. You can find it [here](https://github.com/CargoSense/ex_aws). What do you think?

**Comment by stavro** [comment]
Yes, I think it would be much better.  It would also allow us to support the latest v4 signature for all regions, closing https://github.com/stavro/arc/issues/3.

**Comment by JustMikey** [comment]
Yeah, exactly. Not only `erlcloud` lacks proper responses and documentation, it's pretty slowly developed, or so it seems to me.

**Comment by stavro** [comment]
Closed via 277c9957c79652e4f94fd2e5608a57de94f6e40f
