### ISSUE TITLE
Issue uploading BLOB

### ISSUE THREAD

**Issue by speeddragon** [stavro/arc#224]
I'm using Arc to upload image files to S3 and it's a great module! But I have one issue that I can't find the solution for it.

If I upload an image file using this javascript code:

```
this.editor.getImageScaledToCanvas().toBlob(blob => {
       const imageFile = new File([blob], 'cover-image.jpg');
 
       let data = new FormData();
       data.append('image', imageFile);
  
       this.props.uploadCoverImage(data);
      }, 'image/jpeg', 1);
```

It works on Chrome and Firefox, but doesn't work on Safari. Safari have an issue with `newFile()`.
https://stackoverflow.com/questions/30727052/file-constructor-in-ie-and-safari
https://stackoverflow.com/questions/33821631/alternative-for-file-constructor-for-safari

The object that I receive in Elixir is:

```
%Plug.Upload{content_type: "application/octet-stream",
 filename: "cover-image.jpg",
 path: "/var/folders/x1/b4_f7z_54ysd30fc5kb4llkr0000gn/T//plug-1508/multipart-330453-200552-1"}
```

But I want to use BLOB (Binary Large OBject) so I rewrite the code:

```
this.editor.getImageScaledToCanvas().toBlob(blob => {
       let data = new FormData();
       data.append('image', blob);
  
       this.props.uploadCoverImage(data);
      }, 'image/jpeg', 1);
```

The object that I receive in Elixir is the following:

```
%Plug.Upload{content_type: "image/jpeg", filename: "blob",
  path: "/var/folders/x1/b4_f7z_54ysd30fc5kb4llkr0000gn/T//plug-1508/multipart-336179-885111-1"}
```

And when uploading to S3 `Cover.store({image, uuid})` I receive the following error: `{:error, :invalid_file}`. If I use the same path to upload directly `Cover.store("/var/folders/x1/b4_f7z_54ysd30fc5kb4llkr0000gn/T//plug-1508/multipart-336179-885111-1")`, I still get the error but if I copy the file to another folder (local folder for example) and user `Cover.store("/full/path/file.jpg")` it works.

So, the same file with extension works, but without extension doesn't work.

It's an issue with Arc or I'm missing something ?

Thanks

**Comment by pedep** [comment]
Could this be due to the validation function in your definition? Could you post the source of the `Cover` module?

**Comment by speeddragon** [comment]
Sorry, now I just look silly. 

```
  # Whitelist file extensions:
  def validate({file, _}) do
    ~w(.jpg .jpeg .png) |> Enum.member?(Path.extname(file.file_name))
  end
```

This was the issue :P I think we can close this.

**Comment by pedep** [comment]
Glad you got it working ;)
