### ISSUE TITLE
:http_error, 307, 'Temporary Redirect'

### ISSUE THREAD

**Issue by tispratik** [stavro/arc#23]
I am getting the below error when trying to store files to S3.

```
iex(1)> Myapp.SiteImageUploader.store("path/to/image.jpg")
** (EXIT from #PID<0.703.0>) an exception was raised:
    ** (ErlangError) erlang error: {:aws_error, {:http_error, 307, 'Temporary Redirect', "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>TemporaryRedirect</Code><Message>Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.</Message><Bucket>mybucket-dev</Bucket><Endpoint>mybucket-dev.s3-us-west-2.amazonaws.com</Endpoint><RequestId>801142CBF4589FAC</RequestId><HostId>RJuvEnRxWxmQMBMCLA7Bn1ie+znHQeWhunRFkjk1sjMsARTDeu92N0EmeU8xTOAP2gMR5ydLP1Q=</HostId></Error>"}}
        (erlcloud) src/erlcloud_s3.erl:1022: :erlcloud_s3.s3_request/8
        (erlcloud) src/erlcloud_s3.erl:682: :erlcloud_s3.put_object/6
        lib/arc/storage/s3.ex:9: Arc.Storage.S3.put/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
        (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

My hunch is that its related to not able to specify the region? My bucket is in the us-west-2 region.

**Comment by tispratik** [comment]
Seems like erlcloud hardcodes the regions in https://github.com/gleber/erlcloud/blob/master/src/erlcloud_s3.erl as us-west-1
My region is us-west-2

**Comment by tispratik** [comment]
It failed with bucket "Northern California" as well.
But worked when i created a bucket with region "US Standard"

**Comment by stavro** [comment]
Thanks for the report. I will be changing this over to a different s3 library in the next couple weeks, which will fix this for arc.  I would recommend US standard until then

**Comment by tispratik** [comment]
Oh okay, thanks!.

**Comment by stavro** [comment]
Thanks for reporting it though, it is definitely needing more attention to make more apparent

**Comment by stavro** [comment]
Closed via 277c9957c79652e4f94fd2e5608a57de94f6e40f. Please reopen if you find additional issues.

**Comment by dvcrn** [comment]
Having the same problem with 0.2.2. Any workaround for this?

**Comment by stavro** [comment]
@dvcrn For Tokyo, your configuration should look like this:

config :arc,
  bucket: "my-tokyo-bucket"

config :ex_aws,
  region: "ap-northeast-1",
  s3: [
    scheme: "https://",
    host: "s3-ap-northeast-1.amazonaws.com",
    region: "ap-northeast-1"
  ]

config :ex_aws,
  access_key_id: "my_access_key",
  secret_access_key: "my_secret_access_key"

Can you confirm it does not work with the above configuration?

**Comment by dvcrn** [comment]
This works :) Thank you!
