### ISSUE TITLE
Video formats avoid the validate file_extension

### ISSUE THREAD

**Issue by dielume** [stavro/arc#235]
Hello, 
For some reason video extensions like .mov, .mp4 or mkv avoid the validate restriction of @extension_whitelist ~w(.jpg .jpeg .gif .png). This is my uploader code:

```
defmodule ChatroomWeb.ImageUploader do
  use Arc.Definition
  use Arc.Ecto.Definition

  @versions [:thumb]
  @extension_whitelist ~w(.jpg .jpeg .gif .png)

  def __storage do
    Arc.Storage.Local
  end


  def validate({file, _}) do
    file_extension = file.file_name |> Path.extname |> String.downcase
    Enum.member?(@extension_whitelist, file_extension)
  end

  def transform(:thumb, _) do
    {:convert, "-strip -thumbnail 100x100^ -gravity center -extent 100x100 -format png", :png}
  end
 def storage_dir(version, {file, scope}) do
    "uploads/users/#{scope.user_id}"
  end

end 
```

**Comment by pedep** [comment]
Sounds strange.. Can you replicate this problem in a plain new project?

I just had a quick try in one of my apps, and my `qwe.mkv` file got rejected just fine.

Also, are you doing any filename manipulation at any point? Could you try insert a `IO.inspect file` inside the validate function, and post the output?

**Comment by dielume** [comment]
Sorry @pedep was my fault, i am new in elixir and phoenix, only 1 month  😅
the reason was not the video format, it is the length of the file that is more than 8 MB (Elilix Default)
Do you know it is possible to convert this raise error in a constraint?

> the request is too large. If you are willing to process larger requests, please give a :length to Plug.Parsers

**Comment by pedep** [comment]
No problem :smile: 

When you say "raise error in a constraint", do you mean in `arc`, or just anywhere in your application?
The error is originally being raised by `plug`, so you wont be able to intercept it in `arc` itself, you can customize the error by utilizing the `ErrorView` provided by phoenix.
Have a look at https://hexdocs.pm/phoenix/errors.html for a quick rundown.
You can see the error `plug_status` error code being used for your specific error here https://github.com/elixir-plug/plug/blob/master/lib/plug/parsers.ex#L9

Just like the docs say, you should pay attention to the fact that errors are rendered differently in `dev` mode in contrast to `prod`. This is dictated by `debug_errors: false`, as further explained in the docs

**Comment by dielume** [comment]
Many thanks for the answer and your patience @pedep i close the issue
