### ISSUE TITLE
It is possible update all dependencies

### ISSUE THREAD

**Issue by marinho10** [stavro/arc#240]
It is possible update all dependencies because the current dependencies versions is old.

**Comment by pedep** [comment]
Could you elaborate on your issue?

**Comment by marinho10** [comment]
When update dependency httpoison from "~> 0.11.1" to "~> 1.0.0"

- Hex dependency resolution failed because arc (version 0.8.0) requires ~> 0.11

**Comment by marinho10** [comment]
I cloned your arc and i changed/added dependencies to
{:ex_aws, "~> 2.0", optional: true}
{:ex_aws_s3, "~> 2.0", optional: true}

And everithing works fine ...

PS: be careful with arc_ecto that needs to be updated (maybe?)

Can i create one pull request?

**Comment by speeddragon** [comment]
The issue in this case is to update `idna` to a version that don't cause problems with OTP 20.

```
src/idna_unicode_data.erl:13: Warning: key "22331" will be overridden in expression
```

To update idna, we need to update hackney, and to update hackney we need to update ex_aws, and to update ex_aws we need to update arc.

**Comment by pedep** [comment]
By the last "we need to update arc" i assume you mean ex_aws has some breaking changes in the new version, that we need to implement in arc?

**Comment by pedep** [comment]
Alright - I think i got the gist of the issue. I guess we should move the discussion into #242 and see if we can get it up to speed.

**Comment by stavro** [comment]
ExAws updated to `~> 2.0` and released

**Comment by danubekas** [comment]
What about httpoison? 
arc still requires ~> 0.13 while latest version is 1.2.0

**Comment by imranismail** [comment]
Bump... httpoison is still pinned to an old version

**Comment by edouardmenayde** [comment]
Bump: still an issue

**Comment by itSQualL** [comment]
Maybe we should create a new issue
