### ISSUE TITLE
Error: Bucket name was saved with the storage_dir in the bucket

### ISSUE THREAD

**Issue by papakay** [stavro/arc#251]
Hi, please I'm having issue with the way file is stored in the digitalocean space.

The upload works fine but the file the bucket name is stored with the directory.

i.e instead of having **"/uploads/myfile.png"** i got  **"bucket-name/uploads/myfile.png"**.

Please how can i resolve this issue? Thank you.

**Comment by EdoardoLopez** [comment]
Did you solve it? how?
