### ISSUE TITLE
Release newer changes (0.9.0?) to Hex?

### ISSUE THREAD

**Issue by nihalgonsalves** [stavro/arc#254]
There are a [bunch of changes](https://github.com/stavro/arc/compare/v0.8.0...master) under "v0.9.0 (In Progress)" that haven't been released to Hex, and its been nearly 6 months since the last code update. The last release was almost a year and a half ago ([v0.8.0](https://github.com/stavro/arc/releases/tag/v0.8.0)).

Is there a reason `0.9.0` has not been released yet, and would it be possible to release it soon?

I'm particularly interested in having `bucket/0` on the Storage Definition released so I can contribute an update that allows multiple GCS buckets upstream to [arc_gcs](https://github.com/martide/arc_gcs). As long as I have to pull arc directly from Git, that isn't possible.

Thanks!

**Comment by Betree** [comment]
@stavro Would be great to have an answer regarding this. If you don't have the time to maintain Arc anymore I'm sure some people here would be happy to help.

**Comment by kiere** [comment]
The dependency on `ex_aws` 1.x is causing me some dependency conflicts as well.

**Comment by stavro** [comment]
Tagged & released as `0.9.0`
