### ISSUE TITLE
Doesn't work with most recent version of Phoenix?

### ISSUE THREAD

**Issue by sashaafm** [stavro/arc#27]
Hello, I'm trying to use your app and I set up everything like in the README but it keeps giving this error:

== Compilation error on file web/uploaders/attachment.ex ==
** (CompileError) web/uploaders/attachment.ex:2: module Arc.Definition is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    web/uploaders/attachment.ex:2: MyApp.Attachment (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

I've got the 'use Arc.Definition' macro and have the mix.exs file setup correctly as well as the config.exs (I think)

**Comment by stavro** [comment]
Can I see your mix.exs file, specifically where you added your
dependencies, as well as your attachment.ex file?

**Comment by sashaafm** [comment]
# Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [mod: {MyApp, []},
     applications: [:phoenix, :phoenix_html, :cowboy,
                    :phoenix_ecto, :mariaex, :comeonin,
                    :tzdata, :ex_aws, :httpoison]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [{:phoenix, "~> 1.0.3"},
     {:phoenix_ecto, "~> 1.1"},
     {:mariaex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.1"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:cowboy, "~> 1.0"},
     {:comeonin, "~> 1.2"},
     {:timex, "~> 1.0.0-rc3"},
     {:arc, "~> 0.2.2"},
     {:arc_ecto, ">= 0.0.0"},
     {:ex_aws, "~> 0.4.10"},
     {:httpoison, "~> 0.7"}]
  end



defmodule MyApp.Attachment do
  use Arc.Definition

  # Include ecto support (requires package arc_ecto installed):
  # use Arc.Ecto.Definition

  @versions [:original]
  @acl :public_read



  # To add a thumbnail version:
  # @versions [:original, :thumb]

  # Whitelist file extensions:
  # def validate({file, _}) do
  #   ~w(.jpg .jpeg .gif .png) |> Enum.member?(Path.extname(file.file_name))
  # end

  # Define a thumbnail transformation:
  # def transform(:thumb, _) do
  #   {:convert, "-strip -thumbnail 250x250^ -gravity center -extent 250x250 -format png"}
  # end

  # Override the persisted filenames:
  # def filename(version, _) do
  #   version
  # end

  # Override the storage directory:
  def storage_dir(version, {file, scope}) do
    "uploads/tickets/attachments/#{scope.id}"
  end

  # Provide a default URL if there hasn't been a file uploaded
  # def default_url(version, scope) do
  #   "/images/avatars/default_#{version}.png"
  # end
end

**Comment by stavro** [comment]
It feels like something might be wrong with the compilation... Can you try to `rm -r _build/` and then re-run `iex -S mix`, and confirm that the arc library went through compilation?

**Comment by sashaafm** [comment]
`Erlang/OTP 18 [erts-7.0] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]

==> idna (compile)
WARN:  Missing plugins: [rebar3_hex]
==> mimerl (compile)
==> fs (compile)
==> ssl_verify_hostname (compile)
==> ranch (compile)
==> poolboy (compile)
==> decimal
Compiled lib/decimal.ex
Generated decimal app
==> poison
Compiled lib/poison.ex
Compiled lib/poison/decoder.ex
Compiled lib/poison/parser.ex
Compiled lib/poison/encoder.ex
Generated poison app
==> comeonin
warning: the dependency comeonin requires Elixir "~> 1.1" but you are running on v1.1.0-dev
make: 'priv/bcrypt_nif.so' is up to date.
Compiled lib/comeonin/bcrypt/base64.ex
Compiled lib/comeonin/config.ex
Compiled lib/comeonin/bcrypt.ex
Compiled lib/comeonin/messages.ex
Compiled lib/comeonin/password/tools.ex
Compiled lib/comeonin/pbkdf2.ex
Compiled lib/comeonin/pbkdf2/base64.ex
Compiled lib/comeonin/tools.ex
Compiled lib/comeonin/password/common.ex
Compiled lib/comeonin/password.ex
Compiled lib/comeonin.ex
Generated comeonin app
==> combine
Compiled lib/combine/helpers.ex
Compiled lib/combine/parser_state.ex
Compiled lib/combine.ex
Compiled lib/combine/parsers/binary.ex
Compiled lib/combine/parsers/base.ex
Compiled lib/combine/parsers/text.ex
Generated combine app
==> certifi (compile)
==> hackney (compile)
==> tzdata
Compiled lib/tzdata/basic_data_map.ex
Compiled lib/tzdata.ex
Compiled lib/tzdata/data_builder.ex
Compiled lib/tzdata/data_loader.ex
Compiled lib/tzdata/ets_holder.ex
Compiled lib/tzdata/far_future_dynamic_periods.ex
Compiled lib/tzdata/parser_organizer.ex
Compiled lib/tzdata/release_reader.ex
Compiled lib/tzdata/release_updater.ex
Compiled lib/tzdata/period_builder.ex
Compiled lib/tzdata/table_data.ex
Compiled lib/tzdata/tzdata_app.ex
Compiled lib/tzdata/util.ex
Compiled lib/tzdata/table_parser.ex
Compiled lib/tzdata/parser.ex
Compiled lib/tzdata/leap_sec_parser.ex
Generated tzdata app
==> timex
Compiled lib/date/interval.ex
Compiled lib/format/format_error.ex
Compiled lib/parse/datetime/helpers.ex
Compiled lib/parse/datetime/parsers.ex
Compiled lib/parse/parse_error.ex
Compiled lib/parse/datetime/tokenizers/directive.ex
Compiled lib/parse/datetime/tokenizer.ex
Compiled lib/parse/datetime/tokenizers/strftime.ex
Compiled lib/parse/datetime/tokenizers/default.ex
Compiled lib/parse/zoneinfo/parser.ex
Compiled lib/timex.ex
Compiled lib/format/time/formatter.ex
Compiled lib/format/time/formatters/humanized.ex
Compiled lib/format/time/formatters/default.ex
Compiled lib/timezone/timezone_info.ex
Compiled lib/date/date_convert.ex
Compiled lib/timezone/database.ex
Compiled lib/date/datetime.ex
Compiled lib/parse/datetime/parser.ex
Compiled lib/timezone/timezone.ex
Compiled lib/date/date.ex
Compiled lib/date/date_format.ex
Compiled lib/format/datetime/formatter.ex
Compiled lib/format/datetime/formatters/strftime.ex
Compiled lib/format/datetime/formatters/default.ex
Compiled lib/timezone/timezone_local.ex
Compiled lib/utils/utils.ex
Compiled lib/time/time.ex
Generated timex app
==> httpoison
Compiled lib/httpoison/base.ex
Compiled lib/httpoison.ex
Generated httpoison app
==> ex_aws
Compiled lib/ex_aws/actions.ex
Compiled lib/ex_aws.ex
Compiled lib/ex_aws/auth/utils.ex
Compiled lib/ex_aws/client.ex
Compiled lib/ex_aws/auth.ex
Compiled lib/ex_aws/config/auth_cache.ex
Compiled lib/ex_aws/config.ex
Compiled lib/ex_aws/dynamo/client.ex
Compiled lib/ex_aws/dynamo/decodable.ex
Compiled lib/ex_aws/dynamo/decoder.ex
Compiled lib/ex_aws/dynamo/encoder.ex
Compiled lib/ex_aws/dynamo/lazy.ex
Compiled lib/ex_aws/dynamo/request.ex
Compiled lib/ex_aws/instance_meta.ex
Compiled lib/ex_aws/json/codec.ex
Compiled lib/ex_aws/json/jsx.ex
Compiled lib/ex_aws/dynamo/encodable.ex
Compiled lib/ex_aws/kinesis/client.ex
Compiled lib/ex_aws/kinesis/request.ex
Compiled lib/ex_aws/kinesis/lazy.ex
Compiled lib/ex_aws/lambda/request.ex
Compiled lib/ex_aws/lambda/client.ex
Compiled lib/ex_aws/request.ex
Compiled lib/ex_aws/request/http_client.ex
Compiled lib/ex_aws/request/httpotion.ex
Compiled lib/ex_aws/request/httpoison.ex
Compiled lib/ex_aws/s3/lazy.ex
Compiled lib/ex_aws/s3/parsers.ex
Compiled lib/ex_aws/s3/request.ex
Compiled lib/ex_aws/s3/utils.ex
Compiled lib/ex_aws/s3/client.ex
Compiled lib/ex_aws/s3/impl.ex
Compiled lib/ex_aws/sqs/client.ex
Compiled lib/ex_aws/s3.ex
Compiled lib/ex_aws/sqs/impl.ex
Compiled lib/ex_aws/sqs/request.ex
Compiled lib/ex_aws/sqs.ex
Compiled lib/ex_aws/utils.ex
Compiled lib/mix/tasks/tail.ex
Compiled lib/ex_aws/lambda/impl.ex
Compiled lib/ex_aws/kinesis/impl.ex
Compiled lib/ex_aws/lambda.ex
Compiled lib/ex_aws/kinesis.ex
Compiled lib/ex_aws/dynamo/impl.ex
Compiled lib/ex_aws/dynamo.ex
Generated ex_aws app
==> arc
Compiled lib/arc.ex
lib/arc/definition.ex:2: warning: variable options is unused
lib/arc/actions/url.ex:40: warning: variable options is unused
Compiled lib/arc/definition.ex
Compiled lib/arc/actions/url.ex
Compiled lib/arc/definition/storage.ex
lib/arc/definition/versioning.ex:16: warning: variable extension is unused
Compiled lib/arc/definition/versioning.ex
Compiled lib/arc/exceptions.ex
Compiled lib/arc/file.ex
lib/arc/actions/store.ex:20: warning: variable definition is unused
lib/arc/actions/store.ex:20: warning: variable msg is unused
lib/arc/actions/store.ex:20: warning: variable scope is unused
Compiled lib/arc/actions/store.ex
Compiled lib/arc/processor.ex
lib/arc/storage/local.ex:10: warning: variable options is unused
Compiled lib/arc/storage/local.ex
lib/arc/storage/s3.ex:30: warning: variable options is unused
Compiled lib/arc/storage/s3.ex
Compiled lib/arc/transformations/convert.ex
lib/mix/tasks/g.ex:16: warning: variable model_destination is unused
Compiled lib/mix/tasks/g.ex
Generated arc app
==> cowlib (compile)
==> cowboy (compile)
==> plug
Compiled lib/plug.ex
Compiled lib/plug/adapters/cowboy.ex
Compiled lib/plug/builder.ex
Compiled lib/plug/conn/adapter.ex
Compiled lib/plug/conn/query.ex
Compiled lib/plug/conn/cookies.ex
Compiled lib/plug/conn/status.ex
Compiled lib/plug/conn/unfetched.ex
Compiled lib/plug/conn/utils.ex
Compiled lib/plug/conn/wrapper_error.ex
Compiled lib/plug/adapters/test/conn.ex
Compiled lib/plug/adapters/translator.ex
Compiled lib/plug/adapters/cowboy/handler.ex
Compiled lib/plug/crypto.ex
Compiled lib/plug/crypto/key_generator.ex
Compiled lib/plug/crypto/message_encryptor.ex
Compiled lib/plug/crypto/message_verifier.ex
Compiled lib/plug/error_handler.ex
Compiled lib/plug/conn.ex
Compiled lib/plug/csrf_protection.ex
Compiled lib/plug/debugger.ex
Compiled lib/plug/head.ex
Compiled lib/plug/html.ex
Compiled lib/plug/exceptions.ex
Compiled lib/plug/method_override.ex
Compiled lib/plug/logger.ex
Compiled lib/plug/parsers.ex
Compiled lib/plug/parsers/json.ex
Compiled lib/plug/parsers/urlencoded.ex
Compiled lib/plug/request_id.ex
Compiled lib/plug/router.ex
Compiled lib/plug/router/utils.ex
Compiled lib/plug/session.ex
Compiled lib/plug/session/store.ex
Compiled lib/plug/session/ets.ex
Compiled lib/plug/session/cookie.ex
Compiled lib/plug/ssl.ex
Compiled lib/plug/static.ex
Compiled lib/plug/supervisor.ex
Compiled lib/plug/test.ex
Compiled lib/plug/upload.ex
Compiled lib/plug/parsers/multipart.ex
Compiled lib/plug/adapters/cowboy/conn.ex
Compiled lib/plug/mime.ex
Generated plug app
==> phoenix_html
Compiled lib/phoenix_html.ex
Compiled lib/phoenix_html/engine.ex
Compiled lib/phoenix_html/tag.ex
Compiled lib/phoenix_html/link.ex
Compiled lib/phoenix_html/safe.ex
Compiled lib/phoenix_html/form_data.ex
Compiled lib/phoenix_html/form.ex
Generated phoenix_html app
==> phoenix
Compiled lib/mix/tasks/compile.phoenix.ex
Compiled lib/mix/tasks/phoenix.digest.ex
Compiled lib/mix/phoenix.ex
Compiled lib/mix/tasks/phoenix.gen.channel.ex
Compiled lib/mix/tasks/phoenix.gen.html.ex
Compiled lib/mix/tasks/phoenix.gen.json.ex
Compiled lib/mix/tasks/phoenix.gen.secret.ex
Compiled lib/mix/tasks/phoenix.routes.ex
Compiled lib/mix/tasks/phoenix.gen.model.ex
Compiled lib/mix/tasks/phoenix.server.ex
Compiled lib/phoenix.ex
Compiled lib/phoenix/code_reloader.ex
Compiled lib/phoenix/code_reloader/proxy.ex
Compiled lib/phoenix/code_reloader/server.ex
Compiled lib/phoenix/config.ex
Compiled lib/phoenix/controller/pipeline.ex
Compiled lib/phoenix/digester.ex
Compiled lib/phoenix/endpoint.ex
Compiled lib/phoenix/controller.ex
Compiled lib/phoenix/endpoint/adapter.ex
Compiled lib/phoenix/controller/logger.ex
Compiled lib/phoenix/endpoint/cowboy_handler.ex
Compiled lib/phoenix/endpoint/cowboy_websocket.ex
Compiled lib/phoenix/endpoint/server.ex
Compiled lib/phoenix/endpoint/watcher.ex
Compiled lib/phoenix/naming.ex
Compiled lib/phoenix/exceptions.ex
Compiled lib/phoenix/pubsub.ex
Compiled lib/phoenix/pubsub/pg2.ex
Compiled lib/phoenix/pubsub/pg2_server.ex
Compiled lib/phoenix/param.ex
Compiled lib/phoenix/endpoint/render_errors.ex
Compiled lib/phoenix/router.ex
Compiled lib/phoenix/router/resource.ex
Compiled lib/phoenix/router/route.ex
Compiled lib/phoenix/router/console_formatter.ex
Compiled lib/phoenix/router/scope.ex
Compiled lib/phoenix/socket/message.ex
Compiled lib/phoenix/socket.ex
Compiled lib/phoenix/pubsub/local.ex
Compiled lib/phoenix/channel/server.ex
Compiled lib/phoenix/channel.ex
Compiled lib/phoenix/router/helpers.ex
Compiled lib/phoenix/supervisor.ex
Compiled lib/phoenix/socket/transport.ex
Compiled lib/phoenix/template.ex
Compiled lib/phoenix/template/engine.ex
Compiled lib/phoenix/template/eex_engine.ex
Compiled lib/phoenix/template/exs_engine.ex
Compiled lib/phoenix/template/html.ex
Compiled lib/phoenix/test/conn_test.ex
Compiled lib/phoenix/transports/long_poll.ex
Compiled lib/phoenix/transports/serializer.ex
Compiled lib/phoenix/transports/long_poll_serializer.ex
Compiled lib/phoenix/transports/long_poll_server.ex
Compiled lib/phoenix/test/channel_test.ex
Compiled lib/phoenix/utils.ex
Compiled lib/phoenix/transports/websocket_serializer.ex
Compiled lib/phoenix/token.ex
Compiled lib/phoenix/transports/websocket.ex
Compiled lib/phoenix/view.ex
Generated phoenix app
==> phoenix_live_reload
Compiled lib/phoenix_live_reload/channel.ex
Compiled lib/phoenix_live_reload/socket.ex
Compiled lib/phoenix_live_reload/live_reloader.ex
Generated phoenix_live_reload app
==> mariaex
Compiled lib/mariaex/cache.ex
Compiled lib/mariaex/coder.ex
Compiled lib/mariaex/connection/tcp.ex
Compiled lib/mariaex/structs.ex
Compiled lib/mariaex/connection.ex
Compiled lib/mariaex/messages.ex
Compiled lib/mariaex/protocol.ex
Generated mariaex app
==> ecto
Compiled lib/ecto.ex
Compiled lib/ecto/adapter.ex
Compiled lib/ecto/adapter/migration.ex
Compiled lib/ecto/adapter/transaction.ex
Compiled lib/ecto/adapter/storage.ex
Compiled lib/ecto/adapters/connection.ex
Compiled lib/ecto/adapters/postgres/connection.ex
Compiled lib/ecto/adapters/postgres/datetime.ex
Compiled lib/ecto/adapters/sql/query.ex
Compiled lib/ecto/migration.ex
Compiled lib/ecto/migration/runner.ex
Compiled lib/ecto/exceptions.ex
Compiled lib/ecto/migrator.ex
Compiled lib/ecto/model.ex
Compiled lib/ecto/model/autogenerate.ex
Compiled lib/ecto/model/dependent.ex
Compiled lib/ecto/model/callbacks.ex
Compiled lib/ecto/pool.ex
Compiled lib/ecto/poison.ex
Compiled lib/ecto/pools/poolboy.ex
Compiled lib/ecto/pools/poolboy/worker.ex
Compiled lib/ecto/pools/sojourn_broker/codel.ex
Compiled lib/ecto/pools/sojourn_broker.ex
Compiled lib/ecto/pools/sojourn_broker/timeout.ex
Compiled lib/ecto/pools/sojourn_broker/worker.ex
Compiled lib/ecto/query/api.ex
Compiled lib/ecto/query.ex
Compiled lib/ecto/query/builder.ex
Compiled lib/ecto/adapters/sql.ex
Compiled lib/ecto/adapters/postgres.ex
Compiled lib/ecto/changeset/relation.ex
Compiled lib/ecto/adapters/mysql.ex
Compiled lib/ecto/embedded.ex
Compiled lib/ecto/log_entry.ex
Compiled lib/ecto/adapters/sql/sandbox.ex
Compiled lib/ecto/query/builder/distinct.ex
Compiled lib/ecto/query/builder/filter.ex
Compiled lib/ecto/query/builder/from.ex
Compiled lib/ecto/query/builder/group_by.ex
Compiled lib/ecto/adapters/mysql/connection.ex
Compiled lib/ecto/query/builder/limit_offset.ex
Compiled lib/ecto/query/builder/join.ex
Compiled lib/ecto/query/builder/lock.ex
Compiled lib/ecto/query/builder/order_by.ex
Compiled lib/ecto/query/builder/preload.ex
Compiled lib/ecto/query/builder/select.ex
Compiled lib/ecto/query/builder/update.ex
Compiled lib/ecto/query/inspect.ex
Compiled lib/ecto/query/planner.ex
Compiled lib/ecto/queryable.ex
Compiled lib/ecto/repo/assoc.ex
Compiled lib/ecto/repo.ex
Compiled lib/ecto/repo/preloader.ex
Compiled lib/ecto/repo/model.ex
Compiled lib/ecto/repo/supervisor.ex
Compiled lib/ecto/storage.ex
Compiled lib/ecto/type.ex
Compiled lib/ecto/repo/queryable.ex
Compiled lib/ecto/schema.ex
Compiled lib/ecto/association.ex
Compiled lib/ecto/changeset.ex
Compiled lib/ecto/model/timestamps.ex
Compiled lib/ecto/model/optimistic_lock.ex
Compiled lib/ecto/migration/schema_migration.ex
Compiled lib/ecto/datetime.ex
Compiled lib/ecto/uuid.ex
Compiled lib/mix/ecto.ex
Compiled lib/mix/tasks/ecto.gen.migration.ex
Compiled lib/mix/tasks/ecto.gen.repo.ex
Compiled lib/mix/tasks/ecto.create.ex
Compiled lib/mix/tasks/ecto.drop.ex
Compiled lib/mix/tasks/ecto.migrate.ex
Compiled lib/mix/tasks/ecto.rollback.ex
Generated ecto app
lib/arc_ecto/definition.ex:2: warning: variable options is unused
==> arc_ecto
Compiled lib/arc_ecto/definition.ex
Compiled lib/arc_ecto.ex
Compiled lib/arc_ecto/model.ex
lib/arc_ecto/type.ex:11: warning: variable definition is unused
lib/arc_ecto/type.ex:11: warning: this clause cannot match because a previous clause at line 4 always matches
lib/arc_ecto/type.ex:13: warning: variable definition is unused
lib/arc_ecto/type.ex:19: warning: variable definition is unused
Compiled lib/arc_ecto/type.ex
Generated arc_ecto app
==> phoenix_ecto
Compiled lib/phoenix_ecto.ex
Compiled lib/phoenix_ecto/json.ex
Compiled lib/phoenix_ecto/plug.ex
Compiled lib/phoenix_ecto/html.ex
Generated phoenix_ecto app
==> s21sec_portal
Compiled lib/s21sec_portal.ex
Compiled lib/s21sec_portal/repo.ex
Compiled web/channels/user_socket.ex
Compiled web/controllers/auth.ex
web/uploaders/attachment.ex:31: warning: variable file is unused
web/uploaders/attachment.ex:31: warning: variable version is unused
Compiled web/uploaders/attachment.ex
Compiled web/web.ex
web/models/user.ex:56: warning: function put_pass_hash/1 is private, @doc's are always discarded for private functions
Compiled web/models/user.ex
Compiled web/models/ticket_message.ex
Compiled web/models/ticket.ex
Compiled web/models/service.ex
Compiled web/controllers/admin_controller.ex
Compiled web/controllers/page_controller.ex
Compiled web/controllers/service_controller.ex
web/controllers/session_controller.ex:3: warning: unused alias User
Compiled web/controllers/session_controller.ex
web/controllers/ticket_message_controller.ex:7: warning: unused alias Ticket
web/controllers/ticket_message_controller.ex:6: warning: unused alias User
Compiled web/controllers/ticket_message_controller.ex
Compiled web/router.ex
Compiled lib/s21sec_portal/endpoint.ex
web/controllers/user_controller.ex:66: warning: variable user is unused
Compiled web/controllers/ticket_controller.ex
Compiled web/controllers/user_controller.ex
Compiled web/views/error_view.ex
web/views/layout_view.ex:5: warning: unused alias User
Compiled web/views/layout_view.ex
Compiled web/views/admin_view.ex
Compiled web/views/page_view.ex
Compiled web/views/session_view.ex
Compiled web/views/service_view.ex
web/views/user_view.ex:7: warning: unused import Plug.Conn
Compiled web/views/user_view.ex
web/templates/ticket/index.html.eex:5: warning: variable f is unused
web/templates/ticket/index.html.eex:22: warning: variable f is unused
web/views/ticket_view.ex:4: warning: unused alias DateTime
Compiled web/views/ticket_view.ex`

**Comment by stavro** [comment]
and you're still getting the error when running `iex -S mix`?

**Comment by sashaafm** [comment]
It works now. Thanks! Was this my problem or arc's?

**Comment by sashaafm** [comment]
Sorry for using the issues section for support, but I think I've done everything correctly but my files do not upload to S3. I receive a {:ok, "filename.png"} as expected by the examples but it does not upload to my S3 bucket

**Comment by stavro** [comment]
If you want to use a Frankfurt region, you must add the following to your config:

```elixir
config :arc,
  virtual_host: true

config :ex_aws,
  s3: [
    scheme: "https://",
    host: "s3.eu-central-1.amazonaws.com",
    region: "eu-central-1"
  ]
```

**Comment by stavro** [comment]
Please let me know if you find any more issues.  Good luck!
