### ISSUE TITLE
Support for additional S3 upload options and/or built-in support for MIME types

### ISSUE THREAD

**Issue by dmarkow** [stavro/arc#30]
S3 defaults to `application/octet-stream` for any files uploaded without a `Content-Type` header. As a result, linking to any file uploaded via Arc causes the browser to download the file instead of viewing it in the browser (PDFs, JPGs, etc.). It appears that other upload libraries (CarrierWave for example) set the MIME type based on the filename before uploading. Plug.MIME has `path/1` which will give you the mime type for the given filename (though that would introduce a dependency on Plug).

As an alternative, or maybe in addition, it would be great to add another overridden function, similar to `storage_dir/2`, where you could return additional S3 PUT options (right now, `Arc.Storage.S3.put/3` hardcodes the options list to `[acl: acl]`, but it could be something along the lines of `[acl: acl] ++ definition.upload_options(version, {file, scope})` or something like that). This way, if MIME support wasn't built in, the end user could still examine the filename and provide a `content_type` option if necessary.

Thoughts? I'm happy to submit a pull request for either or both of these but wanted to check in first. Thanks!

**Comment by stavro** [comment]
Thanks @dmarkow, I'm super busy this week, but I will look into this more next week and let you know what direction we should head :)

Happy holidays!

**Comment by blitzstudios** [comment]
I submitted a pull request where by default it auto-detects the mime-type based on filename and applies it to the file, so images will show up instead of download.  Plug would need to be a dependency in this case - https://github.com/stavro/arc/pull/39

**Comment by stavro** [comment]
There is now preliminary support for explicitly specifying object headers via https://github.com/stavro/arc/commit/ed996ceaccf89fcf9c9b96d2dabba899cfa4f4f2.

I will consider automatically applying the header in the library in the future, but I didn't want to add Plug as a dependency yet.  The Readme and generated upload though include the Plug function necessary (though commented out) to apply the Plug MIME type.

Thanks!
