### ISSUE TITLE
connection error with version 0.2.x

### ISSUE THREAD

**Issue by lau** [stavro/arc#34]
In the new version with ex_aws instead of erlcloud, I get a connection error.
If the S3 bucket is in region other than US east, do you need to specify that in the configuration?

**Comment by stavro** [comment]
Yes, you will need to specify the region in the configuration for ex_aws if
it is non-standard.

Sorry! I thought I added it to the changelog, but I may have missed it.  I
will update it when I get back in town on Tuesday.

**Comment by lau** [comment]
Hi. What is a standard region? Is it assumed that everyone is using just one region?

Good, I would like to know how to add it. Until then I'll stay on the old version.

**Comment by stavro** [comment]
The default settings for `ex_aws` assume US Standard (`us-east-1`).

To use a different region, try adding this to your config:

```
config :ex_aws,
  region: "eu-central-1"
```

**Comment by lau** [comment]
Thanks, I'll let you know once I try upgrading again how it went.

**Comment by lau** [comment]
Hi. It didn't work :/ Have you tested it with another region than US east?

**Comment by tomjoro** [comment]
could it be related to this issue in ex_aws? https://github.com/CargoSense/ex_aws/issues/103

You need to specify all 3 of the parameters because they are not deep merged:

config :ex_aws, :s3,
  scheme: "https://",
  host: "s3.amazonaws.com",
  region: "us-east-1"

**Comment by stavro** [comment]
I've tested it with Frankfurt and US-West and both seemed to be fine, I just had to add what @tomjoro said to the ex_aws config.

What error message are you getting @lau?

**Comment by lau** [comment]
Could you add a working config (with just the keys removed of course) to the readme or docs? I got connection timeout.

**Comment by stavro** [comment]
Added example to readme: https://github.com/stavro/arc/commit/79e788af081d036a63dbd05490c56503a4ff3ca8

Full config:

```
config :arc,
  bucket: "my-frankfurt-bucket"

config :ex_aws,
  region: "eu-central-1",
  s3: [
    scheme: "https://",
    host: "s3.eu-central-1.amazonaws.com",
    region: "eu-central-1"
  ]

config :ex_aws,
  access_key_id: "my_access_key",
  secret_access_key: "my_secret_access_key"
```

**Comment by lau** [comment]
Hi @stavro 

Thanks. Are you sure it is "s3.eu-central-1.amazonaws.com" and not "s3-eu-central-1.amazonaws.com" ?

With that change it worked for me. I just used sa-east-1 instead of eu-central-1

**Comment by stavro** [comment]
@lau Good find.

Here is the list of documented endpoints:  http://docs.aws.amazon.com/general/latest/gr/rande.html

Both `s3.eu-central-1.amazonaws.com` and `s3-eu-central-1.amazonaws.com` work for Frankfurt, but for Sao Paulo, only `s3-sa-east-1.amazonaws.com` is supported.  I'll add this link to the documentation.
