### ISSUE TITLE
Transformation not working (file not found)

### ISSUE THREAD

**Issue by keslert** [stavro/arc#35]
I'm trying to do a basic transformation but I'm getting the following error:

```
[error] Task #PID<0.797.0> started from #PID<0.793.0> terminating
** (stop) :enoent
    (elixir) lib/system.ex:435: System.cmd("convert", ["/var/folders/2g/b9yxmq5d4bzc1yrxpwpgtdth0000gn/T//plug-1451/multipart-778711-631234-1", "-strip", "-thumbnail", "200x200", "-format", "png", "/var/folders/2g/b9yxmq5d4bzc1yrxpwpgtdth0000gn/T/CXJPJE5N3S7NFJZCIVL67NTHAXACTWRD"], [stderr_to_stdout: true])
    lib/arc/transformations/convert.ex:5: Arc.Transformations.Convert.apply/2
    lib/arc/actions/store.ex:50: Arc.Actions.Store.put_version/3
    (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<2.27415194/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
[error] Ranch protocol #PID<0.793.0> (:cowboy_protocol) of listener Bookroo.Endpoint.HTTP terminated
** (exit) an exception was raised:
    ** (ErlangError) erlang error: :enoent
        (elixir) lib/system.ex:435: System.cmd("convert", ["/var/folders/2g/b9yxmq5d4bzc1yrxpwpgtdth0000gn/T//plug-1451/multipart-778711-631234-1", "-strip", "-thumbnail", "200x200", "-format", "png", "/var/folders/2g/b9yxmq5d4bzc1yrxpwpgtdth0000gn/T/CXJPJE5N3S7NFJZCIVL67NTHAXACTWRD"], [stderr_to_stdout: true])
        lib/arc/transformations/convert.ex:5: Arc.Transformations.Convert.apply/2
        lib/arc/actions/store.ex:50: Arc.Actions.Store.put_version/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
        (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

It seems like this has to do with a missing file. This is my definition file.

```elixir
defmodule Bookroo.BookImage do
  use Arc.Definition
  use Arc.Ecto.Definition

  # To add a thumbnail version:
  @versions [:original, :thumb]

  @extension_whitelist ~w(.jpg .jpeg .gif .png)

  def validate({file, _}) do
    file_extension = file.file_name |> Path.extname |> String.downcase
    Enum.member?(@extension_whitelist, file_extension)
  end

  def transform(:thumb, _) do
    {:convert, "-strip -thumbnail 200x200 -format png"}
  end

  # Override the persisted filenames:
  def filename(version, _) do
    version
  end

  # Override the storage directory:
  def storage_dir(version, {_, scope}) do
    "uploads/books/#{scope.uuid}/"
  end

  # Provide a default URL if there hasn't been a file uploaded
  def default_url(:thumb, _) do
    "http://placehold.it/200x200"
  end
end
```

Any thoughts? Could this have something to do with permissions?

**Comment by stavro** [comment]
Hi Kesler,

I am currently out of town until Tuesday and cannot help debug, but if
you're still seeing issues by then I will help resolve them.  I recently
added some error handling to ImageMagick, but it is possible that an error
in the conversion resulted in no file output, but I'm not sure. Best of
luck!

**Comment by keslert** [comment]
Still experiencing the same issue. I can upload the original file to s3 no problems, just any kind of transformation. I can't even tell that it's the transformation that's causing the problem. It seems more like whatever's supposed to put the file in local temporary storage isn't happening (or at least the path is getting screwed up).

**Comment by tomjoro** [comment]
(not sure if you have tried this, but)... have you tried just running that 'convert' from a console, and using those parameters in the error message? since it's just launching the commands from shell.
try for example "convert --version" should show you version info.

**Comment by keslert** [comment]
@tomjoro Thanks tomjoro! I feel really silly, but the problem was with my local imagemagick setup... we're all good now.

**Comment by johnnyji** [comment]
@keslert I seem to be running into a similar issue, do you still happen to remember what your solution was?

**Comment by stavro** [comment]
Can you paste any error messaging you have?

**Comment by johnnyji** [comment]
@stavro Thanks for the quick response!

I get this:

```
["convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/504.\nconvert: no images defined `/var/folders/9k/3303pj_n28qf84pm83s3dvrh0000gn/T/Q57AN45D6ZXKLSHTTVMLI6BLPTM2WXKE' @ error/convert.c/ConvertImageCommand/3257.\n"]
```

Basically I used `Image.store({%{filename: "example.jpg", binary: <<124, 121 ... >>}, current_user})`. The reason I used `binary` instead of `Plug.Upload` is because I can't post FormData in my circumstance.

The error happens here:

```
def transform(:thumb, _) do
    {:convert, "-strip -size 200x200^ -gravity center -extent 200x200"}
end
```

For some reason the transformation doesn't work when I pass a binary. Any thoughts?
