### ISSUE TITLE
Upload progress

### ISSUE THREAD

**Issue by smeevil** [stavro/arc#38]
Hi,

It would be very nice if the async process could return a progress status.
Either in the form of 15324/2123456 Bytes or as a percentage.

I've been looking at both hackney and httpotion but could not find any hooks regarding this myself.
I hope you might have more insight into it :)

Gerard

**Comment by stavro** [comment]
How large of files are you uploading?  I would suppose a majority of the time spent for the upload is from the browser -> elixir webserver, not from the elixir webserver -> s3.

For the first step, (browser -> webserver), you can implement a progress bar the same way you would for any other upload (example: http://www.sitepoint.com/html5-javascript-file-upload-progress-bar/).

How long are your uploads taking?
