### ISSUE TITLE
s3 for prod and local for dev?

### ISSUE THREAD

**Issue by schurig** [stavro/arc#48]
Hey, is there a way to tell arc to save files locally for the dev environment and to use amazon s3 for production?

**Comment by schurig** [comment]
Solved it:

```elixir
def storage_dir(_version, {_file, scope}) do
  if Mix.env == :dev do
    current_directory = __DIR__
    project_root = String.replace(current_directory, "/web/uploaders", "")
    "#{project_root}/priv/static/system/uploads/#{scope.id}"
  else
    "system/uploads/#{scope.id}"
  end
end

def __storage do
  case Mix.env do
    :dev -> Arc.Storage.Local
    _    -> Arc.Storage.S3
  end
end
```

**Comment by joshuaswilcox** [comment]
Thanks for this!  How do you get the urls to not be relative in dev though? Mine show as `uploads/bottle_images/images....` instead of `http://localhost:4000/uploads/bottle_images/images...`

**Comment by stavro** [comment]
Relative urls should be constructed with a specific Endpoint.

personally, I add a convenience method in my Phoenix Endpoints:

```elixir
defmodule MyApp.Endpoint do
  use Phoenix.Endpoint, otp_app: :my_app

  #plugs here

  def absolute_url(path) do
    Path.join(url(), path)
  end
end
```

then call `MyApp.Endpoint.absolute_url("uploads/bottle_images/images...")` when I desire an absolute url.
