### ISSUE TITLE
Attaching multiple images to Arc.Ecto model

### ISSUE THREAD

**Issue by nav301186** [stavro/arc#52]
Arc allows me to upload multiple image, however I need to access those images using arc.ecto model. As explained in tutorial I added one field ("avatar") to my user model as shown below

``` elixir
schema "users" do
    field :name, :string
    field :age, :integer
    field :gender, :string
    field :user_name, :string
    field :email, :string
    field :crypted_password, :string
    field :password, :string, virtual: true
    **field :avatar, LoginService.Avatar.Type**
    field :token, :string, virtual: true
   timestamps
  end
```

Field "avatar" allows me to access image associated with the user model and I can access the avatar path by with following method:
Avatar.url({user.avatar, user})

 but I can't find a way to associate multiple images to the user **so that I can access those images with "Avatar.url" method** as I accessed avatar image ?

**Comment by stavro** [comment]
In general, when you have a one-to-many (one user can have many images) type of relationship, the images should be extracted into their own model.  In this way, you'll create a first class `Image` (or `Attachment`) model, which has a `user_id` and a `file` attribute.  Each `image` record will have it's own scoped image.

And since these new records are meaningless without their saved attachment, I would also recommend using a UUID type of identifier for the file name.

Approximately how many images will you have scoped to each model?  There are a few different ways of doing this, and I can possibly help put together a demo for it.

**Comment by nav301186** [comment]
Thanks, I need to use 4-5 images per user. Demo would be great !!!

**Comment by nicholaswyoung** [comment]
@nav301186 In your `User` model, use:

```elixir
schema "users" do
  has_many :images, LoginService.UserImage
end
```

This is a normal one-to-many relationship in Ecto. Nothing fancy. Then, in the `Avatar` model:

```elixir
schema "user_images" do
  belongs_to :user, LoginService.User
  field :avatar, LoginService.Avatar.Type
end
```

Obviously, you'll need to create a table for `user_images`. This will allow you to attach many different `UserImages` to a given `User`, and manage the relationship just like you normally would in Ecto.

@stavro I assume we can close this now. I hope the above was correct and helpful.

**Comment by Morganjackson** [comment]
@nicholaswyoung Thanks for this example! I

 I Was able to get a single image saving, but I cant figure out how to get it to work with `<%= file_input df, :image, multiple: true %>`

Do you know if I need to adjust my controller to handle multiple files?

This is my create action:

  ```ruby
def create(conn, %{"post" => post_params}) do
    changeset = Post.changeset(%Post{}, post_params)

    case Repo.insert(changeset) do
      {:ok, _post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: admin_post_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
```

Which works fine without `multiple: true` but I get the following when attempting to upload multiple images:

`Request: POST /admin/posts
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Arc.Actions.Store.store/2
        lib/arc/actions/store.ex:8: Arc.Actions.Store.store(Ap.BlogPost, [%Plug.Upload{content_type: "image/png", filename: "demo-1920x1200.png", path: "/var/folders/3l/j0tny20n2qg0n5zd6rwx8whr0000gn/T//plug-1482/multipart-557305-982633-1"}, %Plug.Upload{content_type: "image/jpeg", filename: "photo-1461611034385-e082102d5c75.jpeg", path: "/var/folders/3l/j0tny20n2qg0n5zd6rwx8whr0000gn/T//plug-1482/multipart-557305-999697-1"}, %Plug.Upload{content_type: "image/jpeg", filename: "photo.JPG", path: "/var/folders/3l/j0tny20n2qg0n5zd6rwx8whr0000gn/T//plug-1482/multipart-557306-7062-1"}])`

**Comment by MikeAndrianov** [comment]
Same thing 😢

**Comment by sc0ttman** [comment]
@Morganjackson Were you ever able to get it working with `file_input ... multiple: true`?
