### ISSUE TITLE
Signed URLs

### ISSUE THREAD

**Issue by lau** [stavro/arc#56]
Has anyone done signed URLs on any regions other than us-east-1 ?

I get `SignatureDoesNotMatch` from amazonaws

I tried

```
config :arc,
  virtual_host: true,
  bucket: "bucketname",
  asset_host: "https://bucketname.s3-eu-west-1.amazonaws.com/"
```

but still get the same error.

**Comment by vishnuixm** [comment]
Am also getting the same error `SignatureDoesNotMatch`

**Comment by stavro** [comment]
Sorry, guys.  It's a bit of a headache.

I tested US regions as well as Frankfurt and they seemed to be working, but clearly it's quite a bit different between each region.

I'll spend some time re-thinking how best to integrate with each region, because it shouldn't be this difficult.

**Comment by tiagoengel** [comment]
Is working fine for me using ```sa-east-1```. 

```elixir
config :ex_aws,
  region: "sa-east-1"
```

There's a [bug](https://github.com/stavro/arc_ecto/issues/31) regarding signed urls and the ```arc_ecto``` package who causes this error that has been fixed just now.
