### ISSUE TITLE
No function clause - transform :noaction and ffmpeg

### ISSUE THREAD

**Issue by britton-jb** [stavro/arc#57]
I'm attempting to use Arc's transformation functionality to reformat audio using FFMPEG before I store them. Currently I'm running into an issue with both the `:noaction` transformation, and the "action" transformation.

When a user uploads a file in the desired format, where I don't need to reformat it, and I attempt the `:noaction` method I get the following error:

```
[error] Task #PID<0.553.0> started from #PID<0.550.0> terminating
** (FunctionClauseError) no function clause matching in Arc.Processor.apply_transformation/2
    (arc) lib/arc/processor.ex:6: Arc.Processor.apply_transformation(%Arc.File{file_name: "audio.wav", path: "/tmp/plug-1458/multipart-862094-378542-2"}, :noaction)
    (arc) lib/arc/actions/store.ex:50: Arc.Actions.Store.put_version/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<2.66792300/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
```

`audio_file.ex`
```elixir
defmodule AudioFile do
  use Arc.Definition

  @extension_whitelist ~w(.wav)

  def acl(_, _), do: :private

  def filename(_, {_, scope}) do
    "#{scope.storage_key}"
  end

  def storage_dir(_, {_, scope}) do
    "#{scope.name}/"
  end

  def transform(_version_atom, {file, _scope}) do
    file_extension = get_file_extension(file)

    if Enum.member?(@extension_whitelist, file_extension) do
      :noaction
    else
      {:ffmpeg, fn(input, output) -> "#{input} -format wav #{output}" end, :wav}
    end
  end

  defp get_file_extension(file) do
    file.file_name |> Path.extname |> String.downcase
  end
end
```

When I attempt the deprecated method listed in `lib/arc/processor.ex :7`, by wrapping the `:noaction` in a tuple like `{:noaction}` 

I instead get what looks like the transform function running multiple times, twice without error, and a third time running without including the parameters at all.

Based on the `lib/arc/processor.ex` file it looks like that function should be defined, and have an appropriately matching pattern.

When attempting to actually run the transformation `{:ffmpeg, fn(input, output) -> "#{input} -format png #{output}" end, :wav}` I run into a similar issue:

```
[error] Task #PID<0.552.0> started from #PID<0.549.0> terminating
** (FunctionClauseError) no function clause matching in Arc.Processor.apply_transformation/2
    (arc) lib/arc/processor.ex:6: Arc.Processor.apply_transformation(%Arc.File{file_name: "mp3_test.mp3", path: "/tmp/plug-1458/multipart-864421-249072-1"}, {:ffmpeg, #Function<1.113334142/2 in AudioFile.transform/2>})
    (arc) lib/arc/actions/store.ex:50: Arc.Actions.Store.put_version/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<2.66792300/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
```

This error doesn't seem to make sense to me given the methods on lines 8 and 12 of `lib/arc/processor.ex` seem to have functions that should match.

I'm wondering I'm misunderstanding how Arc should be used, or if there are other issues at play here.

**Comment by stavro** [comment]
Which version of Arc are you using? That first error message indicates to me you might be on an older version

**Comment by britton-jb** [comment]
That was it. I was running `0.2.2`. Just updated to `0.5.1`, and no issues.

Thanks for the awesome work you've done on this project.

**Comment by stavro** [comment]
:raised_hands: Hooray!

Thanks a bunch.
