### ISSUE TITLE
Upload size 413

### ISSUE THREAD

**Issue by madshargreave** [stavro/arc#62]
Hi

When uploading larger images on my production app, I receive the following error:

413 Request Entity Too Large

How can I lift the maximum upload size and is this done on application layer or NGINX?

**Comment by stavro** [comment]
This looks like an NGINX thing:

http://cnedelcu.blogspot.com/2013/09/nginx-error-413-request-entity-too-large.html

**Comment by stavro** [comment]
Closing this. If you feel it's still a problem with `arc` after checking with NGINX, please re-open.
