### ISSUE TITLE
Transformations can't handle complex command args

### ISSUE THREAD

**Issue by jerodsanto** [stavro/arc#63]
I'm building up an `ffmpeg` command that sets metadata and I can't pass this `transform` in its current state:

```elixir
fn(in, out) -> ~s(-f mp3 -i #{in} -metadata title="The Title" -f mp3 #{out}) end
```

I believe the problem arises in `Arc.Transformations.Convert` where it always takes the `args` variable and sends it to `~w()` before passing it to `System.cmd`. The string in this case is:

```
"-f mp3 -i in -metadata title=\"The Title\" -f mp3 out"
```

Calling `~w()` on that produces:

`["-f", "mp3", "-i", "in", "-metadata", "title=\"The", "Title\"", "-f", "mp3", "out"]`

`ffmpeg` chokes on this because it improperly splits the title in the metadata.

A possible solution: check the type of `args` before sending it to `System.cmd`. If it's a string, pass it to `~w()`. If it's already a list, leave it alone. This would allow me to build up the argument list inside my function and return it instead of a string.

If that solution works for you, I'm happy to PR. Please let me know, thanks.

**Comment by stavro** [comment]
@jerodsanto I would be happy with that proposal! Please do submit a PR, and I'll accept it.

❤️
