### ISSUE TITLE
Delay transformations

### ISSUE THREAD

**Issue by secretfader** [stavro/arc#67]
Would it be possible to store the original upload, but delay transformations until later? 

For instance, video encoding takes forever, especially if the clip is of any significant length. It would make sense to offload this task to a pool of workers, which would handle encoding later on, once the upload (to S3, etc) has completed.

As I understand it, Arc currently runs transformations automatically. For images, that's often fine. But larger files could benefit from manual control.

**Comment by stavro** [comment]
Interesting, and quite a reasonable request given the various file types you may upload.

One of the benefits of synchronous file uploading is that any errors during the transformation are known and surfaced prior to saving anything in the database.  By delaying it, we would have a couple other issues:
  * How to surface errors and provide feedback during the transformation process. 
  * Uploaded files in the database no longer guarantee all versions of the file have been created.  Each version might and could fail independently.

**Comment by nicholaswyoung** [comment]
Would it make sense to delay storing transformed files in the DB until the processing has successfully completed?


In addition to long-run into transforms, I can see this being useful where someone has many original uploads that may need to be reprocessed because media standards changed. Then, they can simply grab the originals and go from there, rather than needing to re-upload.

**Comment by amarsahinovic** [comment]
@nicholaswyoung How did you solve this in the end? I'm in the same situation right now, where I need to process an uploaded file and convert it to several files of different quality. There are dedicated machines for transcoding the files, so I am thinking of using some job processing system like exq or verk to do the processing and then integrate it with arc.

**Comment by nicholaswyoung** [comment]
@amarsahinovic I didn't. I passed over Arc entirely, instead choosing to write an internal framework around the cloud storage driver directly.
