### ISSUE TITLE
Google Cloud Storage

### ISSUE THREAD

**Issue by nicholaswyoung** [stavro/arc#70]
Would you be open to a PR that adds support for Google Cloud Storage?

**Comment by nicholaswyoung** [comment]
@stavro Any interest in this?

**Comment by janjiss** [comment]
@nicholaswyoung @stavro +1 for this. Currently one of my projects is on GCE. I can work on the implementation.

**Comment by sashaafm** [comment]
@janjiss and @stavro I'm also interested in participating in this and I've got my project [https://github.com/sashaafm/gcloudex](url) which could help greatly (@nicholaswyoung had previously suggested the use of this project initially)

**Comment by janjiss** [comment]
@sashaafm Awesome! Will check it out :)

**Comment by stavro** [comment]
Yes - I would be open to a PR that adds an optional dependency for gcloudex as well as a new storage format.
