### ISSUE TITLE
How to use a transformer which doesn't accept an output file name as parameter?

### ISSUE THREAD

**Issue by tute** [stavro/arc#77]
`Arc.Transformations.Convert` expects `program` to leave a temporary-named file in the file system, but for example `soffice` (LibreOffice's converter) doesn't take an output path configuration (only `--outdir`).

With the following configuration

```exs
  def transform(:html, _) do
    {
      :soffice,
      &args/2,
      :html
    }
  end

  def args(input, _output) do
    " --headless --convert-to html #{input} "
  end
```

My application throws:

```
** (File.CopyError) could not copy from /var/folders/g7/dtxf2tc57z71whsmx20slp0h0000gn/T/YC7IUQLEUHTWUPUF77L67YFIE6N22MZA to uploads/documents/html-609W56th.xlsx.html: no such file or directory
```

If I set `--outdir #{System.tmp_dir}` it still doesn't know what file name to look for.

How can we work around this issue?

Thanks for your work on this library! :)

**Comment by tute** [comment]
Thanks for your work on this library! :)

**Comment by stavro** [comment]
As of right now `Arc` **requires** the output of your transformation to be located at the file destination given in the `output` variable.

Since `soffice` does not support this, you may be able to create an executable wrapper in your $PATH (eg. bash script) which takes these proper arguments, runs your transformation, and then moves the file into the correct location.

Something like the following:

soffice-wrapper.sh:

```
#!/bin/bash

soffice --headless --convert-to html $1 --outdir /var/tmp/something/
mv /var/tmp/something/myfile.html $2
```

Then in Arc, call:
```elixir
def transform(:html, _) do
  {:soffice_wrapper, fn(in, out) -> "#{in} #{out}" end, :html}
end
```


If you try this, please let me know if it is successful.

**Comment by stavro** [comment]
Please reopen if this doesn't work and I will help find a solution

**Comment by tute** [comment]
Thanks! This is the script I am using right now, and seems to work well:

```bash
#!/usr/bin/env sh

# `soffice` doesn't allow for output file path option, and arc can't find the
# temporary file to process and copy. This script has a similar argument list as
# what arc expects. See https://github.com/stavro/arc/issues/77.

set -e

function convert {
	soffice \
		--headless \
		--convert-to html \
		--outdir $TMPDIR \
		$1
}

function filter_new_file_name {
	awk -F$TMPDIR '{print $2}' \
	| awk -F" " '{print $1}' \
	| awk -F/ '{print $2}'
}

converted_file_name=$(convert $1 | filter_new_file_name)
cp $TMPDIR/$converted_file_name $2
rm $TMPDIR/$converted_file_name
```

**Comment by stavro** [comment]
👏 👏 👏 👏 👏 

Thanks!

**Comment by stavro** [comment]
The only comment I would add is that you might want to check the exit code of `soffice` and propogate that exit code to the script.  That way Arc will be able to handle failure scenarios a little better.

**Comment by tute** [comment]
Added `set -o pipefail`, as suggested by @bernerdschaefer. Thank you all!

**Comment by ac-asks** [comment]
Sorry to reopen a new thread but how do you guys set the $PATH to run the bash script?

**Comment by ac-asks** [comment]
I'm trying to use the script too as it seems my resulting conversion pngs are getting stuck in my temporary folder. How do you place the bas script in your $PATH? 
Thank you!
