### ISSUE TITLE
Uploading of big files to S3 storage causes out of memory

### ISSUE THREAD

**Issue by floriangrundig** [stavro/arc#78]
Hi, 

when I want to upload some big (ca. 3-6 GB) video files in S3 I get an out of memory exception:

`2016-05-31 12:21:02.694 [error] Task #PID<0.761.0> started from #PID<0.759.0> terminating
** (File.Error) could not read file /tmp/plug-1464/multipart-697199-932634-1: not enough memory
    (elixir) lib/file.ex:244: File.read!/1
    (arc) lib/arc/storage/s3.ex:7: Arc.Storage.S3.put/3
`

What do you think about changing the implementation in a way that we could define a kind of threshold and if a file is bigger than that we're uploading that file in chunks as a multipart-upload instead of a simple 'put_object'? 

See https://aws.amazon.com/blogs/aws/amazon-s3-multipart-upload/

Cheers
florian

**Comment by jamescmartinez** [comment]
Another idea would be to stream to disk as well.

**Comment by stavro** [comment]
Arc now streams files to S3.  Please try `v0.6.0-rc1` and report back with any issues.

Thanks!
