### ISSUE TITLE
Crashing when I commit my form if I'm use scope. maybe it's something I do wrong

### ISSUE THREAD

**Issue by maxgronlund** [stavro/arc#8]
defmodule uploaders/Digiramp.Avatar do

..
..

def filename(version, {file, scope}) do
    "#{scope.id}_#{version}_#{file.file_name}"
  end

from the console

[error] Task #PID<0.951.0> started from #PID<0.949.0> terminating
Function: #Function<0.47797856/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function: nil.id/0
        nil.id()
        (digiramp) web/uploaders/avatar.ex:31: Digiramp.Avatar.filename/2
        (arc) lib/arc/definition/versioning.ex:10: Arc.Definition.Versioning.resolve_file_name/3
        (arc) lib/arc/actions/store.ex:49: Arc.Actions.Store.put_version/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
[error] Ranch protocol #PID<0.949.0> (:cowboy_protocol) of listener Digiramp.Endpoint.HTTP terminated
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function: nil.id/0
        nil.id()
        (digiramp) web/uploaders/avatar.ex:31: Digiramp.Avatar.filename/2
        (arc) lib/arc/definition/versioning.ex:10: Arc.Definition.Versioning.resolve_file_name/3
        (arc) lib/arc/actions/store.ex:49: Arc.Actions.Store.put_version/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3

Same thing with
# Override the storage directory:
  def storage_dir(version, {file, scope}) do
    "uploads/users/avatars/#{scope.id}"
  end

**Comment by stavro** [comment]
Can you share the relevant parts of your controller and model?

**Comment by maxgronlund** [comment]
web/controllers/user_controller.ex

```
def update(conn, %{"id" => id, "user" => user_params}) do
    user      = Repo.get!(User, id)
    changeset = User.changeset(user, user_params)
    case Repo.update(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
  end
end
```

web/models/user.ex

```
defmodule Digiramp.User do
  use Digiramp.Web, :model
  use Arc.Ecto.Model
  #scope = Repo.get(User, 1)
  schema "users" do
    field :name, :string
    field :email, :string
    field :avatar, Digiramp.Avatar.Type

    timestamps
  end

  @required_fields ~w(name email)
  @optional_fields ~w(avatar)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> validate_format(:email, ~r/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/)
    |> validate_length(:username, min: 5)
    |> validate_length(:username, max: 50)
    |> update_change(:email, &String.downcase/1)
    |> unique_constraint(:email)
    #|> validate_unique(:email, on: User.Repo, downcase: true)
    #|> unique_constraint(:email)
   
  end
end
```

**Comment by maxgronlund** [comment]
I uploaded the project here

[Link project on github](https://github.com/maxgronlund/digiramp-stack)

**Comment by stavro** [comment]
@maxgronlund Unfortunately if you want to use the Changeset functionality of Ecto, you must include  the [arc_ecto](https://github.com/stavro/arc_ecto) package which enables you to use `cast_attachments`.


```elixir
  @required_fields ~w(name email)
  @optional_fields ~w()

  @optional_attachment_fields ~w(avatar)

  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> cast_attachments(params, [], @optional_attachment_fields)
    |> validate_format(:email, ~r/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/)
    |> validate_length(:username, min: 5)
    |> validate_length(:username, max: 50)
    |> update_change(:email, &String.downcase/1)
    |> unique_constraint(:email)
  end
```

Try this and let me know if you need additional assistance.  Thanks!  :smile:
