### ISSUE TITLE
Absolute links for local urls 

### ISSUE THREAD

**Issue by tiagoengel** [stavro/arc#80]
What do you think about having absolute links when generating urls for the local storage?

Today the urls are relatives, (without a forward slash at the start) this means that if I try to use it in a page that is not in the website root, it will not be found.

The change is very simple, just need to add a / at the start of the url.

I can't think in any problem it may cause, could also be a configuration if you don't want to change the current behaviour.

**Comment by stavro** [comment]
What are you using for your storage directory?

Adding a forward slash to the beginning wouldn't be enough, I'm afraid.  Many use cases need some sort of transformation to turn the project-directory URLs into a path acceptable from your web server.  And then that relative path needs to know the endpoint details for the host, port, and protocol.

**Comment by tiagoengel** [comment]
During development and tests I'm saving it in the ```download``` folder and adding a Static Plug to serve those files, the problem is that the url is generated like this ```downloads/image.png```.  If i try to use it outside of the website root it will not be found. 

On the other hand, if the url comes with a ```/``` at the start (```/downloads/image.png```)  it will be found in any place I put it.

**Comment by hubertlepicki** [comment]
Guys, what's the author's view on this? I can't find a reason why the paths are relative by default, this looks like a bug to me

**Comment by stavro** [comment]
@hubertlepicki I don't use local storage so it hasn't been on the top of my priority list.  what folder are you saving files in? is it inside of your project directory or a different mounted drive?

**Comment by stavro** [comment]
Closed via https://github.com/stavro/arc/commit/117d43121a5c074271ecae3464779ac12727e222.
