### ISSUE TITLE
Cannot upload file bigger than 700KB to s3 

### ISSUE THREAD

**Issue by rizafahmi** [stavro/arc#81]
Everytime I uploaded file bigger than 700KB, I've got this error:

```
[error] #PID<0.550.0> running AppscoastFm.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /episodes
** (exit) exited in: Task.await(%Task{owner: #PID<0.550.0>, pid: #PID<0.553.0>, ref: #Reference<0.0.1.14482>}, 10000)
    ** (EXIT) time out
```

Did this: `config :arc, version_timeout: 100_000_000 #milliseconds` and 

```
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison,
    length: 100_000_000
```

Please help

**Comment by leejarvis** [comment]
Try increasing `read_timeout` config option for `Plug.Parsers`. It defaults to `15_000` ms and the request will be terminated if it's not fast enough.

**Comment by rizafahmi** [comment]
@leejarvis I added `read_timeout` to `1_000_000` but it's till got that error above.

**Comment by mindhash** [comment]
Hey Guys,
Is this issue resolved? I intend to use Arc in my project and will have files upto 5MB.
Does this occur in all scenarios (file types or others) or specific case?

Thanks.

**Comment by stavro** [comment]
I've uploaded 5mb+ files just fine with the current setup.  However, I will look into this specific issue this week and see if I can put some guidelines together for longer filetypes.

However, for 5mb+ files I would definitely recommend we invest more time into https://github.com/stavro/arc/issues/1, which I could use some help with.

**Comment by jfrolich** [comment]
Also looking forward to this. While #1 is an option, it is not always preferable. I also have issues with uploading very large files currently.

**Comment by stavro** [comment]
Arc now streams files to S3.  Please try `v0.6.0-rc1` and report back with any issues.

I'm going to close this for now - if we determine it's still an issue then it is likely unrelated to the file uploading and more of an issue with the processing of the files.  Either way, I think we need more information
