### ISSUE TITLE
Does arc need to be added to the applications list?

### ISSUE THREAD

**Issue by Linuus** [stavro/arc#84]
Hi!

When I compile for production I get this:

```
[...]
Building release with MIX_ENV=prod.

You have dependencies (direct/transitive) which are not in :applications!

The following apps should be added to :applications in mix.exs:

        arc => arc is missing from my_app

Continue anyway? Your release may not work as expected if these dependencies are required! [Yn]: 
```

Is it necessary to add arc to the applications list as well? If so, we should update the readme :)

If not, can I ignore this warning somehow?

**Comment by stavro** [comment]
Yes, you should add it to the applications list to get rid of the warning.

I'll update the Readme

**Comment by Linuus** [comment]
Thanks!

**Comment by vyorkin** [comment]
is it still relevant? I mean with elixir 1.4 do I still have to manually add arc to applications list?
