### ISSUE TITLE
Removing not used assets

### ISSUE THREAD

**Issue by maxgronlund** [stavro/arc#9]
I notices assets I uploaded to s3 persists when I update my 'avatar'

I don't know if it's a amazon thing or it's something I should/can handle

**Comment by maxgronlund** [comment]
Great I just found it on the roadmap.

**Comment by stavro** [comment]
Can you explain your use case more? I'm trying to gather feedback prior to implementing it. What does your storage paths/filenames look like and when would you like them to be deleted

**Comment by stavro** [comment]
@maxgronlund *ping* - Can you please describe your ideal workflow?

**Comment by Swatto** [comment]
Exactly the same needs. But since the author is not responding, I'm gonna follow the conversation.

From my point of view, when an asset is unused by an update or a delete, it should be removed with all potential sizes created.
