### ISSUE TITLE
ImageMagick format (arc v0.5.2)

### ISSUE THREAD

**Issue by tute** [stavro/arc#90]
ImageMagick man page states:

> By default, the image format of `file' is determined by its magic number.  To specify a particular image format, precede the filename with an image  format name and a colon (i.e. ps:image) or specify the image type as the filename suffix (i.e. image.ps).  Specify 'file' as '-' for standard input or output.

But the temporary file name that `arc` generates use neither of those, and when I try to convert a `pdf` document into a `png` the file format doesn't change, rendering an "invalid png".

How can we fix this?

Thank you very much!

**Comment by tute** [comment]
This is my module:

```elixir
defmodule Prodeal360.PdfUploader do
  use Arc.Definition

  @versions [:original, :png]

  def transform(:png, _) do
    {:convert, "-density 150 -trim -append -quality 100 -sharpen 0x1.0 -format png", :png}
  end

  def filename(version, {file, _scope}) do
    "#{version}-#{file.file_name}"
  end

  def storage_dir(_version, {_file, scope}) do
    "uploads/#{Mix.env}/#{scope.id}"
  end

  def __storage do
    case Mix.env do
      :dev  -> Arc.Storage.Local
      :test -> Arc.Storage.Local
      _     -> Arc.Storage.S3
    end
  end
end
```

**Comment by stavro** [comment]
I'm not sure I follow - `convert` shouldn't need the temporary file to have `.png` extension. 

The *output* of convert is a png, so why would the file need a `png` extension prior to using convert?

**Comment by tute** [comment]
Quoting from the `man` page:

> By default, the image format of `file' is determined by its magic number.

This stands for `pdf` on the original filename.

> To specify a particular image format, precede the filename with an image format name and a colon (i.e. ps:image) or specify the image type as the filename suffix (i.e. image.ps). Specify 'file' as '-' for standard input or output.

Either would work.

When I run `convert` through `arc` the temporary file results in a broken png, or a valid pdf. When I run it myself, appending the `.png` format, then it generates the expected, correct PNG file.

**Comment by stavro** [comment]
So the output of `convert` is a temporary `png` file missing the extension.

However, when the temporary file is moved to the permanent destination (either s3 or local), the `png` extension should be appended.

Is this not the case?

**Comment by tute** [comment]
This is not the case: the output of `convert` without the format in the file name will be the same format as the original file. If we tell convert that the output file has a format of `png`, then it will know to do the translation.

**Comment by tute** [comment]
BTW: thank you for your time thinking through this and maintaining this code! :)

**Comment by stavro** [comment]
> the output of convert without the format in the file name will be the same format as the original file. If we tell convert that the output file has a format of png, then it will know to do the translation.

But in your transformation you have `-format png` which instructs `convert` to format the output file (*regardless of the file extension*) as a png file.  The file extension is irrelevant to the bytes that ImageMagick saves to disk. 

So this is the process:

1.  A PDF file exists on the filesystem
2. Arc runs a transformation with `convert` which will create a temporary file (in the format of a `png`) with no file extension.
3. Arc moves the file to a permanent destination with the `png` extension (specified as the third tuple argument in the transform).

I still don't see where and why this is an issue.

**Comment by tute** [comment]
> But in your transformation you have `-format png` which instructs `convert` to format the output file (regardless of the file extension) as a png file. The file extension is irrelevant to the bytes that ImageMagick saves to disk.

This makes perfect sense, and this had me scratching my chin for a while yesterday. This looks like a bug in ImageMagick to me:

```zsh
% convert \
	/Users/tutec/Sites/thoughtbot/citrusbyte/prodeal360/spikes/original_files/Hyperlinked_Commitment.PDF \
	-density 150 \
	-trim \
	-append \
	-quality 100   \
	-sharpen 0x1.0 \
	-format png \
	out1.png
% file out1.png
out1.png: PNG image data, 542 x 10790, 16-bit/color RGBA, non-interlaced
%
% convert \
	/Users/tutec/Sites/thoughtbot/citrusbyte/prodeal360/spikes/original_files/Hyperlinked_Commitment.PDF \
	-density 150 \
	-trim \
	-append \
	-quality 100   \
	-sharpen 0x1.0 \
	-format png \
	out2
% file out2
out2: PDF document, version 1.4
% convert --version
Version: ImageMagick 6.9.3-7 Q16 x86_64 2016-03-27 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
```

**Comment by stavro** [comment]
Yes - this definitely looks like a bug in ImageMagick:

```
convert test.pdf -format png out
identify out
# => out PDF 612x792 612x792+0+0 16-bit Bilevel Gray 61KB 0.000u 0:00.000
```

Well, 💩. That sucks.

**Comment by stavro** [comment]
Ok let me take a look at that other PR - which would solve this for you.

**Comment by tute** [comment]
Indeed. Their docs explain this behavior appropriately. It's just that the `format` flag seems to not work.

Thanks! :)

**Comment by stavro** [comment]
Can you try this for me?

```elixir
def transform(:png, _) do
    {:convert, fn(input, output) -> "#{input} -density 150 -trim -append -quality 100 -sharpen 0x1.0 png:#{output}" end, :png}
  end
```

**Comment by tute** [comment]
I've tried that, but `arc` is not aware of the new temporary file's path, and it fails when trying to move it elsewhere.

**Comment by stavro** [comment]
> arc is not aware of the new temporary file's path

The path won't change:

```
convert test.pdf png:out
identify out
#=> out PNG 612x792 612x792+0+0 8-bit sRGB 82c 9.09KB 0.000u 0:00.000
```

**Comment by stavro** [comment]
This should be better, and ImageMagick should correctly save this as a png without the extension:

```elixir
def transform(:png, _) do
  transform_func = fn(input, output) ->
    [input, "-density", "150", "-trim", "-append", "-quality", "100", "-sharpen", "0x1.0", "png:#{output}"]
  end

  {:convert, transform_func, :png}
end
```

**Comment by tute** [comment]
This works well! We route around the `convert` bug, and my application code works. I tried this idea somehow differently, as yesterday my code was failing. Thank you, @stavro!
