### ISSUE TITLE
ex_aws version

### ISSUE THREAD

**Issue by gwincr11** [stavro/arc#97]
Hello,

I need to use ex_aws ~> 1.0.0_beta. I would like to use arc, but you currently do not support the new version and syntax of ex_aws, any plans on upgrading? 

The changes seem fairly simple to make if the docs are correct, from what I gather all that is needed is to pass the ex_aws call to the new request method. But I haven't tried it.

Thanks,
Cory

**Comment by stavro** [comment]
Yes - we should definitely stay up-to-date with the latest ex_aws if there is a newer version.

**Comment by stavro** [comment]
The `ex_aws_beta` branch on `arc` is compatible with`ex_aws` beta1.

Please use and provide feedback.  It will be merged once `ex_aws` is released.

**Comment by gwincr11** [comment]
Thanks stavro, I will give it a shot.

**Comment by stavro** [comment]
@gwincr11 Hopefully it worked as expected? Thx

**Comment by gwincr11** [comment]
@stavro so far so good, sorry for not following up. Any plan to add support for ecto arc?

**Comment by stavro** [comment]
Not sure I understand your question... can you clarify?  If you reference that branch from git I don't believe any changes need to be made

**Comment by gwincr11** [comment]
ok I will try it, I was getting a dependency error on the version of arc.

**Comment by stavro** [comment]
Try adding `override: true` and you should be good!

**Comment by gwincr11** [comment]
oh, cool... Override always makes me nervous :)

**Comment by stavro** [comment]
Released arc as `v0.6.0-rc1` to track ExAws.
